import fs from 'node:fs';
const OUT='bench/results/2026-09-29-task5',read=n=>JSON.parse(fs.readFileSync(`${OUT}/${n}.json`,'utf8'));
const sec=read('security'),fnv=read('security-fnv'),db=read('measure'),adv=read('adversarial');
const f=n=>Number(n).toFixed(3),pct=n=>Number(n).toFixed(2),dist=x=>[x.min,x.median,x.p90,x.max].map(pct).join(' / ');
const quant=xs=>{xs.sort((a,b)=>a-b);return {min:xs[0],median:(xs[99]+xs[100])/2,p90:xs[179],max:xs[199]};};
const majority=Object.fromEntries(['coarse2','coarse3','coarse4','B16'].map(k=>[k,quant(sec.seeds.map(s=>100*s.designs[k].bucketComposition.reduce((n,b)=>n+Math.max(...b.values.map(v=>v.rows)),0)/sec.victimRows))]));
fs.writeFileSync(`${OUT}/formula.json`,JSON.stringify({majority,formula:'sum over buckets max company count / N; oracle composition, forced guess, not observed attack'},null,2));
const koreanLike=n=>'all'in n?n.all.some(koreanLike):'any'in n?n.any.some(koreanLike):n.op!=='eq'&&/[\uac00-\ud7af]/u.test(n.value);
const names={plain:'평문',final:'기존 최종안 2비트',coarse3:'회사명 3비트',direct:'고정 위치 판정'};
let s=`# 과제 5 — m1-astra\n\n## 실패·미검증 먼저\n\n- DB 완료 ${db.rows.length}/42 조건·작업, 오류 ${db.errors.length}건. ${db.finished?'전 비교의 count와 정렬된 반환 ID·6칸 값이 평문과 일치.':'측정 진행 중; 완료 아님.'}\n- 앞·뒤 고정 위치 판정의 속도 향상은 아래 실측으로 판단한다. 등장 순번을 저장하는 형식이므로 목표 위치만 안다고 등장 순번까지 바로 알 수는 없다. 배열 탐색과 일부 순번 해시는 남는다.\n- 보안 결과는 회사명 정확 검색 버킷만 관찰하는 제한된 공격 모델이다. 다른 칸, 회사명 부분 검색 토큰, 길이·위치·공동 출현, 검색·쓰기 관찰을 합친 공격과 운영 자료는 측정 안 함. 복원 0%를 안전 근거로 쓰지 않는다.\n- HMAC 시뮬레이션은 키별 균등 버킷 배치의 대용이며 실제 제품의 키 파생을 재현하지 않는다. 기존 FNV 시뮬레이터 결과도 별도 보존했다.\n- C 로캘 한글 LIKE 포함 조건은 †로 표시하고 평문 대비 성능 판정에서 제외한다. 배율은 해당 로컬 실측의 산술값일 뿐이다.\n\n## 조건과 변경 범위\n\nDB: 기존 동일 고객 100,000행·1 scope, 창2 위치 도장 6칸과 행 결속 암호문. 회사명만 3비트로 바꾼 새 research_u.pb_5_coarse3는 pb_4_improved의 원래 16비트 토큰에서 (token >> 29) & 7로 파생했다. 기존 2비트에서 3비트를 복원하지 않았다. 6칸 투영은 name/phone/address/memo/email/company이며 UUID 오름차순 LIMIT 300이다.\n\n고정 위치 판정은 새 research_u.pb_5_match_direct 함수만 사용한다. 시작은 p=0, 끝은 p=n−L을 고정하고 각 조각의 목표 위치에서 저장 도장을 찾는다. 해당 위치와 등장 순번 i의 해시가 같을 때만 통과하며, 불일치하면 그 조각의 등장 순번을 단조 증가시키되 목표 위치를 넘거나 조각이 없으면 종료한다. 포함 검색은 기존 함수를 호출한다. 저장 토큰·도장·위치·암호문은 동일해 추가 저장 누출을 만들지 않았으며 검색 위치 제한도 제거하지 않았다. 이는 구현 차이 설명이며 공격 전반의 보안 인증은 아니다.\n\n측정 ${db.started} ~ ${db.finished??'진행 중'}, 단일 PostgreSQL PID ${db.session.pid}, 모든 계측 SQL의 PID를 매번 단언했다. idleTimeoutMillis=0, 단일 연결. 첫 실행 별도 1회 후 예열2+경로 순환 교차7, 지표별 중앙값. SQL은 요청~응답 왕복이며 서버 실행만의 시간이 아니다. OS 캐시는 비우지 않았다. 락 보유 중 측정했으며 본 작업의 메모리 시뮬레이션은 DB 측정 전에 종료했다. 외부 부하가 전혀 없었다는 별도 계측은 하지 않았다. 지표별 중앙값은 합산되지 않을 수 있다.\n\n새 표 적재·색인 ${f(read('load').totalMs)}ms. 기존 표·함수 수정 및 커밋 없음, 새 표·함수 보존.\n\n|표|행 수|표·색인·TOAST 총 MB|\n|---|---:|---:|\n`;
for(const t of db.tables)s+=`|${t.table}|${t.rows}|${f(Number(t.bytes)/1e6)}|\n`;
s+='\n암호 경로의 저장 총량은 검색 표와 공유 native_verify_main.customers 본문을 한 번 합산한다.\n\n## A. 시드 200개 보안 분포\n\n회사명 16종, 피해 50,000행(원 fixture 앞 절반), 참조 분포는 뒤 50,000행. 알려진 무작위 행은 5/50/500개이며 평가 분모에서 제외한다. 같은 시드 내 비트 수별로 알려진 행 표본을 공유한다. 시드 1~200에서 key=SHA256(task5-key:seed), HMAC-SHA256 버킷을 각각 2/3/4/16비트로 잘랐다. 무작위 행 표본도 시드에 따라 바뀌므로 알려진 행 공격의 분포에는 키 배치와 표본 변동이 모두 포함된다.\n\n복원%는 **알려지지 않은 행의 회사명 값을 맞춘 비율**이며, 16개 서로 다른 값 중 맞춘 비율이 아니다. 오답%도 같은 전체 평가 행 분모이고 나머지는 추측 보류다. 학습한 버킷에 알려진 회사가 정확히 하나일 때만 추측하는 기존 공격 정책이다. 정보가 늘어 여러 회사가 관찰되면 추측을 보류하므로 복원율이 감소할 수 있으며, 이것은 더 강한 공격도 약해진다는 뜻이 아니다. 삽입은 참조 자료의 16개 회사명을 모두 아는 공격자가 값당1/3행의 버킷을 관찰하는 메모리 모사다. 빈도 순위는 피해 버킷 순위와 참조 회사 순위를 일대일 대응시키는 단순 공격이다.\n\n각 칸은 최소 / 중앙값 / p90 / 최대(%), 중앙값은 가운데 두 값 평균, p90은 정렬180번째. 원자료 security.json, 보조 security-fnv.json.\n\n|비트|공격|복원% 분포|오답% 분포|\n|---|---|---|---|\n';
for(const k of ['coarse2','coarse3','coarse4','B16'])for(const a of ['known0.01','known0.1','known1','inserted1','inserted3','frequency']){const r=sec.range[k][a];s+=`|${k}|${a}|${dist(r.recoveredPct)}|${dist(r.wrongPct)}|\n`;}
s+='\n### 버킷 배치와 계산 대조\n\n단독 버킷은 정확히 한 회사만 들어 있는 버킷이다. 80% 쏠림은 비어 있지 않은 버킷 중 하나라도 한 회사가 행의 80% 이상을 차지하는 경우이며, 단독 버킷도 포함한다.\n\n|비트|단독 버킷 존재 시드 비율|80% 쏠림 존재 시드 비율|단독 버킷 행 비율 분포|버킷별 최빈값 강제 추측 정답률 계산|\n|---|---:|---:|---|---|\n';
for(const k of ['coarse2','coarse3','coarse4','B16']){const r=sec.range[k];s+=`|${k}|${pct(r.singletonLayoutPct)}%|${pct(r.dominant80LayoutPct)}%|${dist(r.singletonRows)}|${dist(majority[k])}|\n`;}
s+='\n버킷 b의 회사 집합을 V_b, 회사 v의 행 수를 n_v라 하면, 모든 16개 값을 삽입해 아는 기존 단일값 추측 공격의 복원율은 **Σ_b 1[|V_b|=1] Σ_{v∈V_b} n_v / N**이다. 4비트 폭×200시드 모두 행 단위 공격 결과와 반올림 오차0.00501%p 이내로 일치했다. 값당 3행도 같은 결정적 버킷을 반복 관찰하므로 값당1행과 동일했다.\n\n마지막 열은 **Σ_b max_{v∈V_b} n_v / N**의 계산값이다. 버킷별 구성과 실제 빈도까지 아는 공격자가 모든 행에 최빈값을 강제 추측하는 가정이므로 위에서 실험한 공격과 구분한다. 단독 버킷이 없더라도 편향된 값 추측은 가능함을 보이는 계산이며 실측 공격 성공률로 제시하지 않는다.\n\n|해시 대용|2비트 삽입 복원 중앙/p90/최대|3비트|4비트|\n|---|---|---|---|\n';
for(const [name,r]of [['HMAC',sec],['기존 FNV',fnv]])s+=`|${name}|${['coarse2','coarse3','coarse4'].map(k=>{const v=r.range[k].inserted1.recoveredPct;return [v.median,v.p90,v.max].map(pct).join(' / ')}).join('|')}|\n`;
s+='\n## B. 동일 세션 DB 결과\n\n없는 회사명은 3비트의 가장 큰 버킷에서 새로 탐색했다: '+JSON.stringify(adv.chosen)+'。이 값은 평문에서0건이다.\n\n';
for(const group of ['coarse','affix']){
 s+=`### ${group==='coarse'?'회사명 3비트 7조건':'앞·뒤 고정 위치 14조건'}\n\n|조건|조건 전문|평문 일치 수|후보(2비트 / 비교 경로)|\n|---|---|---:|---|\n`;
 for(const r of db.rows.filter(r=>r.group===group&&r.mode==='count'))s+=`|${r.name}${koreanLike(r.node)?'†':''}|${r.condition.replaceAll('|','\\|')}|${r.matches}|${r.candidates.final} / ${r.candidates[group==='coarse'?'coarse3':'direct']}|\n`;
 for(const mode of ['count','list']){
  s+=`\n${mode==='count'?'count':'목록300'} 중앙값(ms), 모든 행 SQL1회, count 수신1행/인증복호화0칸, 목록은 반환 행과 동일한 수신 행 및 행당6칸 인증복호화.\n\n|조건|평문 SQL / 전체 (=1배)|기존2비트 SQL / 전체|비교 SQL / 전체|비교 SQL 평문배율|비교 전체 평문배율|비교 SQL / 기존 SQL|\n|---|---:|---:|---:|---:|---:|---:|\n`;
  for(const r of db.rows.filter(r=>r.group===group&&r.mode===mode)){const p=r.summary.plain,b=r.summary.final,c=r.summary[group==='coarse'?'coarse3':'direct'];s+=`|${r.name}${koreanLike(r.node)?'†':''}|${f(p.db)} / ${f(p.total)}|${f(b.db)} / ${f(b.total)}|${f(c.db)} / ${f(c.total)}|${f(c.sqlRatio)}|${f(c.ratio)}|${f(c.db/b.db)}|\n`;}
 }
}
s+='\n### 구간별 상세와 첫 실행\n\n후보는 SQL 판정 전 토큰 조건을 통과한 행 수이며 목록 LIMIT까지 실제 방문한 수가 아니다. 수신은 드라이버가 받은 행 수, 반환은 최종 목록 길이(count는 숫자1개)다. 준비=첫 SQL 전, 중간=SQL 사이, 후처리=마지막 SQL 응답 뒤. 모든 값은 ms이다.\n\n|조건·작업|경로|후보 / 수신 / 반환|인증칸 / SQL회|준비|SQL|중간|후처리|전체|첫 SQL / 전체|\n|---|---|---|---|---:|---:|---:|---:|---:|---:|\n';
for(const r of db.rows)for(const [p,v]of Object.entries(r.summary))s+=`|${r.name} ${r.mode}|${names[p]}|${r.candidates[p]} / ${v.appRows} / ${r.returned}|${v.decrypts} / ${v.sql}|${f(v.pre)}|${f(v.db)}|${f(v.between)}|${f(v.post)}|${f(v.total)}|${f(r.first[p].db)} / ${f(r.first[p].total)}|\n`;
const improved=db.rows.filter(r=>r.group==='affix'&&r.summary.direct.db<r.summary.final.db),coarse=db.rows.filter(r=>r.group==='coarse'&&r.summary.coarse3.db<r.summary.final.db);
s+=`\n## 가설 검증\n\n|가설|결과|근거|\n|---|---|---|\n|3비트가2비트와 같은 누출 수준이다|기각|삽입 공격 복원 중앙값0→10.03%, 단독 버킷 존재25.5→92%|\n|3비트가 모든 질의에 큰 개선을 준다|기각|14 조건·작업 중 SQL 감소 ${coarse.length}개; 전체 수치는 위 표|\n|위치만 고정하면 앞·뒤 검색이 크게 빨라진다|지지되지 않음|28 조건·작업 중 SQL 감소 ${improved.length}개, 순번·배열 탐색 비용 유지|\n|바꾼 판정과3비트 경로가 평문과 같다|${db.rows.length===42?'통과':'미완료'}|${db.rows.length} 조건·작업×3경로×10실행, count 또는 정렬 ID·6칸 값 대조|\n|전체 DB 백업의 복원이 어렵다|미검증|회사명 정확 토큰 이외의 누출 결합 공격 제외|\n\n## 재현과 증거\n\n- 메모리: rtk proxy node --import tsx bench/research-task5/security.ts (HMAC 200시드). 기존 FNV 재현은 security-fnv.ts.\n- DB 재측정: rtk proxy node --import tsx bench/research-task5/db.ts measure (보존된 표·함수 사용, 새 load 재실행 금지).\n- 보고: rtk proxy node bench/research-task5/report.mjs. 원자료 ${OUT}/measure.json, cases.json, adversarial.json, load.json, security.json, security-fnv.json, formula.json.\n\n## 결론 3줄\n\n1. 회사명3비트는 일부 후보를 줄여 드문 회사 검색을 개선하지만, 200시드 공격에서는2비트보다 단독 버킷과 값 복원이 크게 늘어 보안 동등 개선으로 권하지 않는다.\n2. 앞·뒤 목표 위치를 고정한 판정은 저장 누출을 추가하지 않고 평문과 일치했으나, 현재 등장 순번·배열 구조에서 일관된 큰 속도 개선은 확인되지 않았다.\n3. 로컬 합성 fixture 결과이며 운영 보장·보안 인증이 아니다; 연구 표·함수와 반복 원자료를 보존했다.\n`;
fs.writeFileSync('.local/research/task5-m1-astra.md',s);
console.log(JSON.stringify({rows:db.rows.length,finished:db.finished,coarseFaster:coarse.length,affixFaster:improved.length,reportBytes:Buffer.byteLength(s),majority}));
