import {readFileSync} from 'node:fs';
import {makeProbes,learn,type Strategy} from '../../final-review/r9-impl/probes.js';
import {attacker} from '../../final-review/r9-impl/attack.js';
import {ActiveCodec} from '../../final-review/r9-impl/codec.js';
import {assert,BitCodec,rows,norm,scope,shuffled,save,stats,hash} from './common.js';
const raw=rows(),prior=JSON.parse(readFileSync('bench/results/2026-09-29-final-review/r9-impl/bits.json','utf8'));
const result:any={started:new Date().toISOString(),complete:false,rows:raw.length,reference:10000,victims:1000,databaseAccess:false,fixtureReplay:true,fixtureDigest:hash('sha256',raw.map(r=>r.id).join('\n')),attack:[],selection:[],search:[],summary:[],validation:{cryptoChecks:0,priorAttackMatches:0,noFalseNegatives:0,priorCandidateMatches:0},protocol:'Same fixture seed, key, scope, sample, N=10/100/1000 and attack as prior bits experiment; substring width only; exact and proof unchanged'};
for(const field of ['phone','address'] as const){
 const values=raw.map(r=>norm(r[field])),ref=raw.slice(0,10000).map(r=>r[field]),victim=raw.slice(10000,11000),freq=[new Map<string,number>(),new Map<string,number>(),new Map<string,number>()];
 for(const value of values){const chars=Array.from(value);for(let width=2;width<=4;width++){const terms=new Set<string>();for(let j=0;j+width<=chars.length;j++)terms.add(chars.slice(j,j+width).join(''));for(const term of terms)freq[width-2].set(term,(freq[width-2].get(term)??0)+1);}}
 const queries:{term:string;width:number;matches:number;group:string}[]=[];
 for(let width=2;width<=4;width++){const all=[...freq[width-2]],rare=all.filter(([,n])=>n<=10),chosen=shuffled(rare,20260929+width).slice(0,200);result.selection.push({field,width,distinct:all.length,minFrequency:Math.min(...all.map(([,n])=>n)),rareAvailable:rare.length,rareSampled:chosen.length});for(const [term,matches]of chosen)queries.push({term,width,matches,group:'rare-1-10'});if(!chosen.length)for(const [term,matches]of all.sort((a,b)=>a[1]-b[1]||a[0].localeCompare(b[0])).slice(0,200))queries.push({term,width,matches,group:'lowest-frequency-control'});}
 for(const bits of field==='phone'?[16,12,10]:[16,12]){
  const codec=new BitCodec(field,bits);for(const row of raw.slice(0,5)){result.validation.cryptoChecks+=await codec.validate(row[field]);if(bits!==10)assert.deepEqual(codec.tokens(row[field]),new ActiveCodec(field,'product',scope,bits).tokens(row[field]));}
  for(const strategy of ['whole-values','packed-pieces'] as Strategy[]){const probes=makeProbes(ref,field,strategy),pieces=probes.map(v=>codec.pieces(v)),views=probes.map(v=>({tokens:codec.tokens(v),plainBytes:Buffer.byteLength(v),length:Array.from(norm(v)).length}));for(const n of [10,100,1000]){const mapping=learn(pieces.slice(0,n),views.slice(0,n).map(v=>v.tokens)),predict=attacker({field,pieces:v=>codec.pieces(v)},ref,probes.slice(0,n),views.slice(0,n),mapping);let correct=0,characters=0,totalCharacters=0,mostly=0,capped=0,graph=0;for(const row of victim){const truth=norm(row[field]),g=predict({tokens:codec.tokens(row[field]),plainBytes:Buffer.byteLength(row[field]),length:Array.from(truth).length}),cs=Array.from(truth),gs=Array.from(g.value),ok=cs.filter((c,i)=>gs[i]===c).length;correct+=Number(g.value===truth);characters+=ok;totalCharacters+=cs.length;mostly+=Number(ok>=cs.length*.8);capped+=Number(g.graphCapped);graph+=Number(g.source==='graph');}if(bits!==10){assert.equal(correct,prior.attack.find((r:any)=>r.bits===bits&&r.field===field&&r.strategy===strategy&&r.n===n).values);result.validation.priorAttackMatches++;}result.attack.push({field,bits,strategy,n,correct,total:victim.length,pct:correct/victim.length*100,characters,totalCharacters,mostly,capped,graph,mapped:mapping.size,correctMapping:[...mapping].filter(([t,p])=>codec.token(p)===t).length});}}
  const qt=queries.map(q=>codec.queryTokens(q.term)),wanted=new Set(qt.flat()),postings=new Map<string,number[]>([...wanted].map(t=>[t,[]]));for(let i=0;i<raw.length;i++){for(const t of codec.tokens(raw[i][field]))postings.get(t)?.push(i);if(i%1000===999)codec.clear();}
  const search=queries.map((q,qi)=>{const lists=qt[qi].map(t=>postings.get(t)!).sort((a,b)=>a.length-b.length),sets=lists.slice(1).map(xs=>new Set(xs)),ids=lists[0].filter(i=>sets.every(s=>s.has(i))),candidate=new Set(ids);let matches=0;for(let i=0;i<values.length;i++)if(values[i].includes(q.term)){matches++;assert(candidate.has(i));}assert.equal(matches,q.matches);result.validation.noFalseNegatives+=matches;return {...q,field,bits,candidates:ids.length,factor:ids.length/matches};});
  result.search.push(...search);for(const width of [2,3,4]){const qs=search.filter(q=>q.width===width),base=result.search.filter((q:any)=>q.field===field&&q.bits===16&&q.width===width);result.summary.push({field,bits,width,group:qs[0]?.group,n:qs.length,candidates:stats(qs.map(q=>q.candidates)),factor:stats(qs.map(q=>q.factor)),relative16:stats(qs.map((q,i)=>q.candidates/base[i].candidates)),ratioOfMeans:qs.reduce((s,q)=>s+q.candidates,0)/base.reduce((s:number,q:any)=>s+q.candidates,0),worst:qs.map((q,i)=>({...q,base:base[i].candidates,ratio:q.candidates/base[i].candidates})).sort((a,b)=>b.ratio-a.ratio)[0]});}
  if(field==='phone'&&bits!==10){const old=JSON.parse(readFileSync('bench/results/2026-09-29-followup/token-bits/phone.json','utf8'));for(const s of search){assert.equal(s.candidates,old.search.find((x:any)=>x.bits===bits&&x.term===s.term&&x.width===s.width).candidates);result.validation.priorCandidateMatches++;}}
  save('bits',result);console.log(JSON.stringify({field,bits,attack:result.attack.filter((r:any)=>r.field===field&&r.bits===bits),summary:result.summary.filter((r:any)=>r.field===field&&r.bits===bits)}));
 }
}
result.complete=true;result.finished=new Date().toISOString();save('bits',result);console.log('COMPLETE memory bits');
