import {readFileSync} from 'node:fs';
import {compileStampQuery,keyArray} from '../../../src/core/stamp-query.js';
import {rewrite} from '../r9-impl/variants.js';
import {learn} from '../../final-review/r9-impl/probes.js';
import {attacker} from '../../final-review/r9-impl/attack.js';
import {assert,BitCodec,rows,norm,rng,fields,ring,scope,save,hash,cap3} from './common.js';
const seed=714029,data=rows(),victim=data.slice(0,10000),reference=data.slice(10000,20000),assign=rng(seed),schedule=Array.from({length:1000},()=>Math.floor(assign()*fields.length));
type Query={global:number;term:string;pieces:string[];tokens:string[];head:string[];keys:string[]};
function words(values:string[]){const m=new Map<string,number>();for(const value of values)for(const word of value.match(/[\p{L}\p{N}]+/gu)??[]){const w=norm(word),n=Array.from(w).length;if(n>=2&&n<=45)m.set(w,(m.get(w)??0)+1);}return [...m];}
function draw(list:[string,number][],random:()=>number){const target=random()*list.reduce((s,[,n])=>s+n,0);let sum=0;for(const [word,count]of list){sum+=count;if(sum>target)return word;}return list.at(-1)![0];}
/** Partial bundles: intersect positive plaintext sets, then use only provable absences.
 * Min/max are always transmitted, so tokens outside those bounds were absent.
 * No secret token-to-piece lookup or victim plaintext is available here. */
function partialMapping(qs:Query[]){const possible=new Map<string,Set<string>>();for(const q of qs)for(const t of q.head){const ps=new Set(q.pieces),old=possible.get(t);possible.set(t,old?new Set([...old].filter(p=>ps.has(p))):ps);}const result=new Map<string,string>();for(const [t,ps]of possible){for(const q of qs){const absent=!q.head.includes(t)&&(q.pieces.length<=3||q.head.length<3||BigInt(t)<BigInt(q.head[0])||BigInt(t)>BigInt(q.head.at(-1)!));if(absent)for(const p of q.pieces)ps.delete(p);}if(ps.size===1)result.set(t,[...ps][0]);}const count=new Map<string,number>();for(const p of result.values())count.set(p,(count.get(p)??0)+1);return new Map([...result].filter(([,p])=>count.get(p)===1));}
const result:any={started:new Date().toISOString(),complete:false,databaseAccess:false,fixtureRows:data.length,victims:victim.length,reference:reference.length,seed,scheduleHash:hash('sha256',JSON.stringify(schedule)),variantSourceHash:hash('sha256',readFileSync('bench/lasthour/r9-impl/variants.ts')),results:[],queries:[],validation:{rewriteCases:0,unchangedProofPayloads:0,p2SameTokenUnions:0,productCryptoChecks:0},threat:'Snapshot candidate tokens and ciphertext byte lengths; known query plaintext labels as in attack-extra; no proof keys/arrays/salts/positions or victim plaintext used by predictors',algorithms:['Original attack-extra query-bundle signature+byte-length dictionary; cap3 uses only provably complete observed bundles','Learn opaque token labels from query membership; partial bundles use positive intersections and min/max exclusion; existing reference dictionary+phone graph attacker'],limitations:['Partial-bundle attack is conservative, not optimal; reconstruction rates are lower bounds','P2 exposes both head and tail; union identical to P0','Proof piece keys do not change; full T4 position leakage is not removed','One fixture, key and query distribution; no SQL time measurement']};
for(const [fi,field]of fields.entries()){
 const codec=new BitCodec(field),truth=victim.map(r=>r[field]),ref=reference.map(r=>r[field]),dictionary=words(ref),random=rng(seed+fi),queries:Query[]=[];
 for(const value of truth.slice(0,3))result.validation.productCryptoChecks+=await codec.validate(value);
 for(let i=0;i<1000;i++)if(schedule[i]===fi){const term=draw(dictionary,random),pieces=codec.queryPieces(term),tokens=codec.queryTokens(term),head=cap3(tokens),proof=await compileStampQuery(ring,codec.p,scope,{op:'contains',value:term});
  const q={text:'select 1 where "i"."tokens_ab12" @> $1::bigint[] and proof($2,$3,$4)',values:[tokens,keyArray(proof.keys),proof.offsets,proof.length]},p1=rewrite(q,false),p2=rewrite(q,true);assert.deepEqual(p1.values[0],head);assert.deepEqual(p2.values[0],head);assert.deepEqual(p1.values.slice(1),q.values.slice(1));assert.deepEqual(p2.values.slice(1,4),q.values.slice(1));const union=[...head,...(p2.values[4]??[])].sort();assert.deepEqual(union,[...tokens].sort());result.validation.rewriteCases++;result.validation.unchangedProofPayloads+=2;result.validation.p2SameTokenUnions++;
  queries.push({global:i+1,term,pieces,tokens,head,keys:proof.keys.map(k=>Buffer.from(k).toString('hex'))});
 }
 const tokenSets=truth.map(v=>new Set(codec.tokens(v))),refCounts=new Map<string,number>(),refBytes=new Map<string,Set<number>>();for(const v of ref){const n=norm(v);refCounts.set(n,(refCounts.get(n)??0)+1);const b=refBytes.get(n)??new Set();b.add(Buffer.byteLength(v));refBytes.set(n,b);}const ordered=[...refCounts].sort((a,b)=>b[1]-a[1]).map(([v])=>v),refSets=new Map(ordered.map(v=>[v,new Set(codec.pieces(v))])),byBytes=new Map<number,string[]>();for(const v of ordered)for(const b of refBytes.get(v)!){const vs=byBytes.get(b)??[];vs.push(v);byBytes.set(b,vs);}
 for(const observations of [10,100,1000]){
  const qs=queries.filter(q=>q.global<=observations),allRefMasks=new Map<string,bigint>();for(const v of ordered){const ps=refSets.get(v)!;let mask=0n;qs.forEach((q,i)=>{if(q.pieces.every(p=>ps.has(p)))mask|=1n<<BigInt(i);});allRefMasks.set(v,mask);}
  for(const path of ['P0','P1','P2'] as const){const partial=path==='P1',wire=qs.map(q=>partial?q.head:q.tokens),complete=qs.filter(q=>!partial||q.pieces.length<=3||q.head.length<3),mapping=partial?partialMapping(qs):learn(qs.map(q=>q.pieces),wire);
   const masks=new Map<string,bigint>();for(const v of ordered){const ps=refSets.get(v)!;let mask=0n;complete.forEach((q,i)=>{if(q.pieces.every(p=>ps.has(p)))mask|=1n<<BigInt(i);});masks.set(v,mask);}const byMask=new Map<bigint,string[]>();for(const v of ordered){const mask=masks.get(v)!,vs=byMask.get(mask)??[];vs.push(v);byMask.set(mask,vs);}
   let completeMask=0n;qs.forEach((q,i)=>{if(complete.includes(q))completeMask|=1n<<BigInt(i);});
   const predict=attacker({field,pieces:v=>codec.pieces(v)},ref,[],[],mapping);let bundleCorrect=0,mappedCorrect=0,bundleChars=0,mappedChars=0,totalChars=0,bundleMostly=0,mappedMostly=0,graphCapped=0,partialConstraintCorrect=0,partialConstraintChars=0,partialConstraintMostly=0;
   for(let i=0;i<truth.length;i++){const v=truth[i],actual=Array.from(norm(v)),bytes=Buffer.byteLength(v);let mask=0n;complete.forEach((q,j)=>{if(q.tokens.every(t=>tokenSets[i].has(t)))mask|=1n<<BigInt(j);});const prior=byBytes.get(bytes)?.[0]??ordered[0],guess=(byMask.get(mask)??[]).find(v=>refBytes.get(v)!.has(bytes))??prior,g=predict({tokens:[...tokenSets[i]].sort(),plainBytes:bytes}),a=Array.from(guess),b=Array.from(g.value),ac=actual.filter((c,j)=>a[j]===c).length,bc=actual.filter((c,j)=>b[j]===c).length;bundleCorrect+=Number(guess===norm(v));mappedCorrect+=Number(g.value===norm(v));bundleChars+=ac;mappedChars+=bc;totalChars+=actual.length;bundleMostly+=Number(ac>=actual.length*.8);mappedMostly+=Number(bc>=actual.length*.8);graphCapped+=Number(g.graphCapped);
    // Even a partial query excludes any reference value that contains the whole
    // known query when the victim lacks a transmitted token. Do not discard this
    // valid negative evidence merely because omitted token labels are unknown.
    let observedMask=0n;qs.forEach((q,j)=>{if((partial?q.head:q.tokens).every(t=>tokenSets[i].has(t)))observedMask|=1n<<BigInt(j);});const constrained=partial?(byBytes.get(bytes)??[]).find(v=>{const m=allRefMasks.get(v)!;return (m&~observedMask)===0n&&(m&completeMask)===(observedMask&completeMask);})??prior:guess;const cc=actual.filter((c,j)=>Array.from(constrained)[j]===c).length;partialConstraintCorrect+=Number(constrained===norm(v));partialConstraintChars+=cc;partialConstraintMostly+=Number(cc>=actual.length*.8);
   }
   const r={field,path,observations,fieldObservations:qs.length,transmittedTokens:wire.reduce((n,ts)=>n+ts.length,0),distinctTokens:new Set(wire.flat()).size,proofKeyTransmissions:qs.reduce((n,q)=>n+q.keys.length,0),distinctProofKeys:new Set(qs.flatMap(q=>q.keys)).size,fullyObservedBundles:complete.length,mappedTokens:mapping.size,correctlyMappedTokens:[...mapping].filter(([t,p])=>codec.token(p)===t).length,rows:truth.length,bundleCorrect,mappedCorrect,bundlePct:bundleCorrect/truth.length*100,mappedPct:mappedCorrect/truth.length*100,bundleChars,mappedChars,totalChars,bundleMostly,mappedMostly,graphCapped,partialConstraintCorrect,partialConstraintPct:partialConstraintCorrect/truth.length*100,partialConstraintChars,partialConstraintMostly};result.results.push(r);console.log(JSON.stringify(r));
  }
  const a=result.results.at(-3),b=result.results.at(-1);assert.deepEqual({...a,path:'P2'},b);
 }
 result.queries.push(...queries.map(q=>({field,global:q.global,term:q.term,tokenCount:q.tokens.length,headCount:q.head.length,proofKeys:q.keys.length})));save('observation',result);codec.clear();
}
assert.equal(result.queries.length,1000);assert.equal(result.validation.p2SameTokenUnions,1000);result.complete=true;result.finished=new Date().toISOString();save('observation',result);console.log('COMPLETE memory observation');
