import {readFileSync} from 'node:fs';
import {createHmac,hkdfSync} from 'node:crypto';
import {profiles,descriptorBytes,searchPieces,searchTokens} from '../../../src/core/search-tokens.js';
import {frame} from '../../../src/core/bytes.js';
import {assert,rows,BitCodec,ring,scope,hex,norm,save} from './common.js';
const raw=rows(),cases=JSON.parse(readFileSync('bench/results/2026-09-29-final-return/cases.json','utf8')),leaves=new Map<string,any>();
function visit(n:any,source:string){if(n.all)n.all.forEach((c:any)=>visit(c,source));else if(n.any)n.any.forEach((c:any)=>visit(c,source));else if(n.field==='phone'){const id=JSON.stringify(n),q=leaves.get(id)??{...n,source:[]};q.source.push(source);leaves.set(id,q);}}
cases.forEach((c:any)=>visit(c.node,c.name));
const exactProfile=profiles('customers','phone',{type:'text',search:{exact:true}})[0],root=Buffer.from(hkdfSync('sha384',ring.key,new Uint8Array(),frame(['sealql/index/v3',ring.keyScopeId,descriptorBytes(exactProfile)]),48)),prefix=BigInt(createHmac('sha384',root).update(frame(['scope',scope])).digest().readUInt32BE());
function exact(v:string){const raw=createHmac('sha384',root).update(frame(['value',scope,searchPieces(exactProfile,v)[0]])).digest().readUInt32BE();return String(BigInt.asIntN(64,(prefix<<32n)|BigInt((raw>>>16)*65536)));}
const exactTokens=raw.map(r=>exact(r.phone));for(const r of raw.slice(0,5))assert.equal(exact(r.phone),(await searchTokens(ring,scope,exactProfile,searchPieces(exactProfile,r.phone)))[0]);
const output:any={started:new Date().toISOString(),complete:false,databaseAccess:false,rows:raw.length,sourceCases:55,queries:[...leaves.values()],results:[],validation:{productExactRows:5,noFalseNegatives:0},interpretation:'Phone leaves isolated from 55 Boolean conditions; other fields unchanged. Ratio estimates only per-candidate work under a fixed cost, not measured SQL latency.'};
for(const bits of [16,12,10]){const codec=new BitCodec('phone',bits),queries=[...leaves.values()].map(q=>({...q,tokens:q.op==='eq'?[exact(q.value)]:[...new Set(searchPieces(codec.p,q.value,q.op).map(p=>codec.token(hex(p))))],matches:0,candidates:0}));for(let i=0;i<raw.length;i++){const value=norm(raw[i].phone),tokens=new Set(codec.tokens(raw[i].phone));for(const q of queries){const candidate=q.op==='eq'?exactTokens[i]===q.tokens[0]:q.tokens.every((t:string)=>tokens.has(t)),matches=q.op==='eq'?value===norm(q.value):q.op==='startsWith'?value.startsWith(norm(q.value)):q.op==='endsWith'?value.endsWith(norm(q.value)):value.includes(norm(q.value));q.matches+=Number(matches);q.candidates+=Number(candidate);assert(!matches||candidate);output.validation.noFalseNegatives+=Number(matches);}if(i%1000===999)codec.clear();}for(const q of queries){const base=bits===16?q:output.results.find((r:any)=>r.bits===16&&r.op===q.op&&r.value===q.value);output.results.push({...q,tokens:undefined,bits,extra:q.candidates-base.candidates,ratio:base.candidates?q.candidates/base.candidates:q.candidates===0?1:null});}save('phone-queries',output);}
output.complete=true;output.finished=new Date().toISOString();save('phone-queries',output);console.log(JSON.stringify(output.results));console.log('COMPLETE phone query counts');
