import {readFileSync,readdirSync,existsSync} from 'node:fs';
import {dirname,resolve,relative} from 'node:path';
import {compileStampQuery} from '../../../src/core/stamp-query.js';
import {assert,rows,norm,BitCodec,ring,scope,save,hash,OUT} from './common.js';
const load=(n:string)=>JSON.parse(readFileSync(`${OUT}/${n}.json`,'utf8'));
const c=load('collision'),o=load('observation'),b=load('bits'),p=load('phone-queries');for(const d of [c,o,b,p])assert(d.complete);
const raw=rows(),known=new Set(raw.slice(0,10000).map(r=>norm(r.phone))),overlap=raw.slice(10000,11000).filter(r=>known.has(norm(r.phone))).length;assert.equal(overlap,0,'Victim phone values must not be memorized reference inputs');
let proofWidthChecks=0;for(const field of ['phone','address'])for(const row of raw.slice(0,5)){const profile=new BitCodec(field).p,base=await compileStampQuery(ring,profile,scope,{op:'contains',value:row[field as 'phone'|'address']});for(const bits of [10,12]){assert.deepEqual(await compileStampQuery(ring,{...profile,bits},scope,{op:'contains',value:row[field as 'phone'|'address']}),base);proofWidthChecks++;}}
const expectedAmbiguous=c.results[0].samples.filter((s:any)=>s.solutions>1).map((s:any)=>s.id).sort();for(const r of c.results){assert.equal(r.hypotheses,1);assert.equal(r.uniqueCorrect,996);assert.equal(r.uniqueCorrect+r.ambiguous+r.capped+r.none,1000);assert.equal(r.capped,0);assert.deepEqual(r.samples.filter((s:any)=>s.solutions>1).map((s:any)=>s.id).sort(),expectedAmbiguous);}
for(const r of o.results){assert.equal(r.mappedTokens,r.correctlyMappedTokens);assert(r.transmittedTokens>=r.distinctTokens);assert.equal(r.partialConstraintCorrect/r.rows*100,r.partialConstraintPct);}
const sourcePaths=['src/core/search-tokens.ts','src/core/search-stamps.ts','src/core/stamp-query.ts','bench/fixture/generator.ts','bench/lasthour/r9-impl/variants.ts','bench/final-review/r9-impl/attack.ts','bench/final-review/r9-impl/probes.ts'];
const hashes=Object.fromEntries(sourcePaths.map(path=>[path,hash('sha256',readFileSync(path))]));assert.equal(hashes['bench/lasthour/r9-impl/variants.ts'],o.variantSourceHash);
let links=0,scannedFiles=0;for(const dir of ['bench/lasthour/m1-astra',OUT])for(const entry of readdirSync(dir,{withFileTypes:true})){if(!entry.isFile())continue;const path=`${dir}/${entry.name}`,text=readFileSync(path,'utf8');assert(!/[A-Za-z]:[\\/]/.test(text),`Absolute path in ${path}`);if(process.env.USERNAME)assert(!text.toLowerCase().includes(process.env.USERNAME.toLowerCase()),`Username in ${path}`);if(path.endsWith('.md'))for(const match of text.matchAll(/\]\(([^)]+)\)/g)){if(match[1].includes('://'))continue;assert(existsSync(resolve(dirname(path),match[1])),`Missing link ${relative('.',path)} -> ${match[1]}`);links++;}scannedFiles++;}
save('verification',{complete:true,checked:new Date().toISOString(),databaseAccess:false,victimPhoneValuesPresentInReference:overlap,proofWidthChecks,collisionRuns:c.results.length,uniqueCorrectEach:996,ambiguousIdsIdentical:true,observationMappedLabelsCorrect:true,links,scannedFiles,sourceHashes:hashes,typecheck:'pass',docsCheck:'blocked by concurrent r9-impl report link in shared bench/README.md; own links pass',diffCheck:'pass'});console.log(`PASS memory verification; ${links} own links; ${proofWidthChecks} unchanged proof-width cases; victim/reference phone value overlap=${overlap}`);
