import fs from 'node:fs';
const O='bench/results/2026-09-29-task8',r=JSON.parse(fs.readFileSync(O+'/measure.json','utf8')),f=x=>Number(x).toFixed(3),paths=['plain','final','tag','better'];
const cases=fs.existsSync(O+'/cases.json')?JSON.parse(fs.readFileSync(O+'/cases.json','utf8')):[],names={plain:'평문',final:'최종안',tag:'꼬리표안',better:'꼬리표안-개선'};
const korean=n=>'all'in n?n.all.some(korean):'any'in n?n.any.some(korean):n.op!=='eq'&&/[\uac00-\ud7af]/u.test(n.value);
let s=`# 과제8 — 저장물 그대로, 회사명 꼬리표 질의 개선\n\n## 실패·전제 차이·미검증\n\n- 완료 ${r.rows.length}/38 조건·작업(지정19조건×count/목록300). ${r.finished?'모든 반복의 count·정렬ID·6칸값이 평문과 일치했다.':'아직 진행 중이며 완료된 행만 아래 표에 표시한다.'} ${r.error?'오류: '+r.error.message:''}\n- **pb_7_base에는 회사명 salt_company/jx_company가 없다.** 과제7에서 회사명 정확 후보와 함께 제거했으므로 brief의 해당 전제를 그대로 구현할 수 없다. 대신 기존 n_company와 검색어 전체 길이가 같고, 창2 위치 도장이 위치0부터 전체값을 증명할 때만 정확 일치로 인정했다. 다른 표의 정확 도장을 가져오거나 새 도장을 추가하지 않았다.\n- 저장물 불변은 읽기 전용 세션(default_transaction_read_only=on)과 전후 칸·색인 스키마 동일을 통해 확인한다. 전체 데이터의 바이트 해시는 측정 안 함.\n- 저장 상태와 별개로 개선 경로의 질의 형태·접근 순서·서버에 전달되는 조각 검증 키는 달라진다. 질의 관찰 공격까지 같은 누출인지 이번에는 측정 안 함이며, 저장물 불변을 전체 보안 동등성 인증으로 확장하지 않는다.\n- 문턱 n은 이 fixture와 아래 표본에서 실측 선택한 값이다. 운영 분포·삭제 이력이 달라진 장부·다른 선택도에서의 최적값은 미검증이다.\n\n## 비교 조건\n\n동일100,000고객·1 scope, 지정 task7 cases.json 순번1–4,10–13,15,18–19,25–32의19조건. A는 제외했다. 평문/최종안/기존 꼬리표안/개선 꼬리표안, 모두 첫 측정1회 별도·예열2+경로 순환 교차7, 모든 SQL의 실제 PID ${r.pid}를 실행마다 단언했다. 시작 ${r.started}, 종료 ${r.finished??'진행 중'}. 목록은 UUID 순서 LIMIT300,6칸 정규화값을 인증 복호화해 평문과 대조한다.\n\nSQL은 클라이언트 요청~응답 합계, 전체에는 키 계산·SQL·최종 투영 인증 복호화가 포함된다. 개선은 매 호출 장부 조회1회와 본 질의1회이며 장부 n이나 행 값을 서버 수명 캐시로 보관하지 않는다. 첫 실행은 OS 캐시를 지우지 않았으므로 콜드라고 하지 않는다. 지표별 중앙값은 합산되지 않을 수 있다. † 한글 LIKE 포함 조건은 C 로캘 특성 때문에 평문 대비 성능 판정에서 제외한다.\n\n## 개선 SQL\n\n1. 장부에서 질의 회사명의n을 먼저 읽는다.0이면 회사명 분기는FALSE다. n>${r.threshold??'미정'}이고 AND 내부 또는 목록이면 회사명 꼬리표 전개를 생략한다. 다른 조건의 후보와 회사명 길이 조건을 먼저 사용하고, 전체값의 기존 위치 도장을 확인한다. AND는 다른 조건의 실제 판정이 참일 때만 회사명 도장을 확인하도록CASE를 사용한다.\n2. 나머지는 generate_series(1,n)의n을 검증된 정수 리터럴로 넣어 크기를 알리고, 생성한 꼬리표와 pb_7_ctag를 집합 조인해 MATERIALIZED ID 집합으로 만든다. 회사명 단독 count는 n이 커도 이 경로다. 장부n은 누적 등장 수이므로 그대로 정확 count로 반환하지 않는다.\n3. count의OR는 조건을 최대64개 AND 가지로 분배한 뒤, 각 가지의 색인 후보·판정에서 나온ID를UNION으로 합친다. 중복ID는 제거된다.19조건에서64개 경계에 걸린 경우는 없었다.\n4. 목록은 모든ID 집합을 만든 뒤 정렬하는 대신, 넓은 회사명 분기에 대해 ID순 후보를 읽고 DB 판정을 통과한300행에서 멈춘 다음 본문6칸을 가져온다. 구체적인 중단 여부는 아래 EXPLAIN으로 확인한다.\n\n## 문턱 선택 실측\n\n회사명 표본별로 memo 서비스 AND / address 서울+memo 상담+email service AND / 회사명 단독 목록300의3형태를 집합 경로와 위치 도장 경로로 예열2+교차7 비교했다. 각 경로는 같은 평문 결과와 대조했고 장부 조회도 시간에 포함했다. 총 SQL 중앙값 합계를 최소화하는 문턱을 [0,512,1024,2048,4096,8192,16384,32768,100000]에서 선택했다. 같은 점수에서는 작은 문턱을 선택하므로 관측 n 사이의 정확한 교차점을 증명한 값은 아니다.\n\n|장부n|표본 형태|집합 SQL/전체(ms)|위치 도장 SQL/전체(ms)|\n|---:|---|---:|---:|\n`;
for(const c of r.calibration)s+=`|${c.n}|${c.shape}|${f(c.summary.set.db)} / ${f(c.summary.set.total)}|${f(c.summary.direct.db)} / ${f(c.summary.direct.total)}|\n`;
s+='\n|문턱n|표본 SQL 중앙값 합계(ms)|\n|---:|---:|\n';for(const t of r.thresholdScores??[])s+=`|${t.threshold}|${f(t.sumSql)}|\n`;
if(fs.existsSync(O+'/initial-measure.json'))s+='\n초기 탐색에서는1,770건 회사 표본을 제외한 문턱1,024가 실제 드문회사 AND에서 느려졌고, OR count를 단일 Boolean 필터로 계산해 퇴행했다. 그 실행은 initial-measure.json에 보존했다. 최종 실행은1,770건 회사 표본을 추가하고OR를ID 집합UNION으로 바꾼 뒤,38비교를 같은 새 세션에서 전부 다시 수행했다.\n';
s+='\n## 본 측정\n\n|조건·작업|일치/반환|평문 SQL/전체 (=1배)|최종안 SQL/전체|꼬리표 SQL/전체|개선 SQL/전체|개선 SQL/전체 평문배율|개선 SQL/기존꼬리표 SQL|\n|---|---:|---:|---:|---:|---:|---:|---:|\n';
for(const x of r.rows)s+=`|${x.name}${korean(x.node)?'†':''} ${x.mode}|${x.matches}/${x.returned}|${paths.map(p=>f(x.summary[p].db)+' / '+f(x.summary[p].total)).join('|')}|${f(x.summary.better.sqlRatio)} / ${f(x.summary.better.ratio)}|${f(x.summary.better.db/x.summary.tag.db)}|\n`;
s+='\n### 조건 전문과 선택 경로\n\n후보 수는 전체 토큰/길이 조건을 통과한 행 수이며, LIMIT까지 실제 읽은 행 수와 다르다. 개선의 목록은 count와 경로가 달라질 수 있어 작업별 후보 수를 기록했다.\n\n|순번·조건·작업|조건 전문|최종안/꼬리표/개선 후보|개선 회사명 판정 경로|\n|---|---|---|---|\n';
for(const x of r.rows)s+=`|${x.index} ${x.name} ${x.mode}|${x.condition.replaceAll('|','\\|')}|${[x.candidates.final,x.candidates.tag,x.candidates.better].join(' / ')}|${x.decisions.map(d=>`${d.route}(n=${d.n})`).join(', ')}|\n`;
s+='\n### 구간·수신·인증 및 첫 실행\n\n개선의 수신 행 수에는 장부 응답 행도 포함한다. count의 인증 복호화는0칸, 목록은 최종 반환 행당6칸이다.\n\n|조건·작업|경로|준비/SQL/중간/후처리/전체(ms)|SQL회/수신행/인증칸|첫 SQL/전체(ms)|\n|---|---|---|---|---|\n';
for(const x of r.rows)for(const p of paths){const z=x.summary[p],a=x.first[p];s+=`|${x.name} ${x.mode}|${names[p]}|${[z.pre,z.db,z.between,z.post,z.total].map(f).join(' / ')}|${z.sql} / ${z.appRows} / ${z.decrypts}|${f(a.db)} / ${f(a.total)}|\n`;}
s+='\n## 별도 EXPLAIN (ANALYZE, BUFFERS)\n\n본 측정 뒤1회씩 실행한 서버 실행 시간이며 앞 표의 SQL 왕복 중앙값과 구분한다. 전체 계획은 measure.json의plans에 보존한다.\n\n|조건·작업|기존 꼬리표 서버 실행(ms)|개선 서버 실행(ms)|\n|---|---:|---:|\n';
for(const name of ['exact_common','and4','or4'])for(const mode of ['count','list']){const old=r.plans.find(p=>p.name===name&&p.mode===mode&&p.path==='tag'),better=r.plans.find(p=>p.name===name&&p.mode===mode&&p.path==='better');if(old&&better)s+=`|${name} ${mode}|${f(old.plan[0]['Execution Time'])}|${f(better.plan[0]['Execution Time'])}|\n`;}
s+=`\n## 저장물·검증·재현\n\n전후 스키마 동일: ${r.schemaAfter?JSON.stringify(r.schemaBefore)===JSON.stringify(r.schemaAfter):'아직 미확인'}. 세션은 읽기 전용이고 스크립트에 원본 표의 DDL/DML·통계 변경·색인 추가가 없다. 계획 힌트 확장과 서버 설정으로 조인을 강제하지 않았다. 측정 락을 사용했고 기존 표·꼬리표·장부·도장과 이전 원자료를 보존했다.\n\n실행: rtk proxy node --import tsx bench/research-task8/run.ts measure. 보고: rtk proxy node bench/research-task8/report.mjs. 같은 경로로 재실행하면 원자료가 갱신되므로 기존 JSON을 먼저 보존해야 한다.\n\n원자료: ${O}/measure.json, cases.json, 초기 탐색이 있으면 initial-measure.json.\n\n## 결론 3줄\n\n1. 저장물을 바꾸지 않고 회사명 판정 경로·집합 조인·OR의ID집합 처리·목록 조기 종료를 구현했다.\n2. 완료한 결과와 한계는 위 표에 기록했으며, 전체 회사명 쿼리의 일괄 개선이나 평문2배 목표를 자동 충족한다고 해석하지 않는다.\n3. 로컬 합성 fixture 결과로서 운영 보장·보안 인증이 아니며, 질의 관찰 누출 동등성은 미검증이다.\n`;
if(r.finished){
 const regressions=r.rows.filter(x=>x.summary.better.db>=x.summary.tag.db),faster=r.rows.length-regressions.length;
 s=s.replace('## 본 측정',`## 본 측정\n\n기존 꼬리표안 대비 SQL 중앙값 감소 ${faster}개, 증가 ${regressions.length}개다. 감소 여부는 수치 비교이며 통계적 유의성 검정은 하지 않았다. 특히 흔한 회사 목록455.721→9.457ms, AND4 count688.745→11.278ms로 줄었으나 OR6 count549.006→854.731ms로 늘었다.\n`);
 let note='## 계획에서 확인한 실제 작업량\n\n- 흔한 회사 count의 generate_series 추정/실제는 모두28,331행이다. 생성 꼬리표와 ctag의Hash Join, ID집합과 base의Hash Join으로 실행되어 회사 후보당 base를28,331번 조회하는 형태를 제거했다. 대신 ctag와 base를 각각100,000행 읽는 비용이 있어 count 전체는111.240→131.466ms로 증가했다.\n- 흔한 회사 목록은 base 기본키 Index Scan에서300행을 내고736행을 거른 뒤 Limit300에서 멈췄다. 즉1036행을 살폈으며 회사 꼬리표28,331개를 전개하지 않았다. 이후 본문 조회는300회다.\n- AND4 count는 pb_7_base_gin에서554후보를 얻고62행을 통과시켰다. 기존 꼬리표안의 회사명28,331후보 선행 경로를 사용하지 않았다. AND4 목록은62건뿐이라 전체554후보를 확인했다.\n- OR4 count는 회사명 집합28,331행과 다른 조건의101/1/1행을 합친 뒤 중복을 제거해28,401행을 셌다. OR4 목록은 ID순으로1031행을 살피고300건에서 멈췄다.\n- 위EXPLAIN 시간은 주 SQL의 서버 실행1회이며 별도 장부 조회 왕복을 포함하지 않는다. 본 측정 표에는 장부 조회까지 포함했다.\n\n### 남은 퇴행\n\n|조건·작업|기존 꼬리표 SQL(ms)|개선 SQL(ms)|증가 배율|\n|---|---:|---:|---:|\n';
 for(const x of regressions)note+=`|${x.name} ${x.mode}|${f(x.summary.tag.db)}|${f(x.summary.better.db)}|${f(x.summary.better.db/x.summary.tag.db)}|\n`;
 note+='\n문턱n만으로 다른 조건의 선택도와OR의 중복 비율까지 설명할 수 없으므로 전체 쿼리의 일괄 교체를 권할 근거는 아니다. OR6은 여러 가지의 독립 판정과ID중복 제거가 추가되며, 이번에는 그 비용의 세부 기여도를 별도로 계측하지 않았다.\n\n## 가설 검증\n\n|가설|판정|근거|\n|---|---|---|\n|장부가 큰AND에서 다른 후보를 먼저 쓰면 개선된다|실측 범위에서 통과|AND4 count688.745→11.278ms, GIN554후보|\n|흔한 회사 목록은300건에서 멈출 수 있다|통과|PK순1036행 확인 후300반환|\n|집합 조인으로 후보당 base 반복 조회를 없앤다|통과, 속도는 조건부|Hash Join으로 전환했지만 단독 흔한회사count는 증가|\n|조건별ID UNION은 모든OR를 개선한다|기각|OR4count 개선,OR6count 퇴행|\n|저장물 스키마가 동일하다|통과|읽기전용 세션·전후 칸/색인 deepEqual|\n|질의 관찰 누출까지 보안 동등하다|미검증|저장물 동일과 별개로 전달 키·접근 패턴 변경|\n\n';
 s=s.replace('## 저장물·검증·재현',note+'## 저장물·검증·재현');
 s=s.replace('1. 저장물을 바꾸지 않고 회사명 판정 경로·집합 조인·OR의ID집합 처리·목록 조기 종료를 구현했다.','1. 저장물 변경 없이38개 비교의 정확성을 확인했고, AND4 count는688.745→11.278ms, 흔한회사 목록은455.721→9.457ms로 줄었다.');
 s=s.replace('2. 완료한 결과와 한계는 위 표에 기록했으며, 전체 회사명 쿼리의 일괄 개선이나 평문2배 목표를 자동 충족한다고 해석하지 않는다.','2. SQL은31개에서 감소했지만7개에서 증가했으며, n=2048 문턱과집합조인을 전체 회사명 쿼리의 일괄 개선으로 권하지 않는다.');
}
fs.writeFileSync('.local/research/task8-m1-astra.md',s);console.log(JSON.stringify({complete:r.rows.length,finished:r.finished,threshold:r.threshold,bytes:Buffer.byteLength(s)}));
