import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {Pool} from 'pg';
import {assertDisposable} from '../../test/disposable.js';
import {normalizeText} from '../../src/core/search-tokens.js';
import {profiles,searchPieces,descriptorBytes} from '../../src/core/search-tokens.js';
import {frame,hex} from '../../src/core/bytes.js';
import {createHmac,hkdfSync} from 'node:crypto';
const n=2000,scope='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',norm=(s:string)=>normalizeText(s,'legacy-text-v1');
const pieces=(s:string)=>{const a=Array.from(norm(s));return [...new Set(a.slice(0,-1).map((c,i)=>c+a[i+1]))];};
function run(dataset:string,values:string[],reference:string[]){const rows=values.map(pieces),frequency=new Map<string,number>();for(const s of reference)for(const p of pieces(s))frequency.set(p,(frequency.get(p)??0)+1);const rank=[...frequency].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));let x=99;const order=Array.from({length:n},(_,i)=>i);for(let i=n-1;i>0;i--){x^=x<<13;x^=x>>>17;x^=x<<5;const j=Math.floor((x>>>0)/2**32*(i+1));[order[i],order[j]]=[order[j],order[i]];}
 return {dataset,rows:n,scenarios:[128,512].map(budget=>{const queries=rank.slice(0,budget).map(x=>x[0]);return {queryBudget:budget,actualQueries:queries.length,known:[1,5,10].map(k=>{const ids=order.slice(0,n*k/100),known=new Set(ids),signatures=new Map<string,string[]>();const vocabulary=new Set(ids.flatMap(i=>rows[i]));for(const p of vocabulary){const s=ids.filter(i=>rows[i].includes(p)).join(',');if(!signatures.has(s))signatures.set(s,[]);signatures.get(s)!.push(p);}let decoded=0,correct=0;const recovered=new Set<string>();for(const q of queries){const sig=ids.filter(i=>rows[i].includes(q)).join(','),guess=signatures.get(sig);if(guess?.length===1){decoded++;if(guess[0]===q){correct++;recovered.add(q);}}}let piecesAll=0,piecesCorrect=0,mostly=0;for(let i=0;i<n;i++){if(known.has(i))continue;const c=rows[i].filter(p=>recovered.has(p)).length;piecesAll+=rows[i].length;piecesCorrect+=c;if(rows[i].length&&c/rows[i].length>=.8)mostly++;}return {knownPct:k,queryLabelRecoveryPct:100*correct/queries.length,queryGuesses:decoded,correctQueryLabels:correct,unknownAdjacentRecoveryPct:100*piecesCorrect/piecesAll,unknownAdjacent80Pct:100*mostly/(n-known.size)};})};})};}
const pool=new Pool({host:'127.0.0.1',port:56439,user:'sealql_test',database:'postgres'});let fixture:string[];
try{await assertDisposable(pool);assert.equal(Number((await pool.query('show port')).rows[0].port),56439);fixture=(await pool.query('select memo_plain from bench_realistic_100k.customers where scope_id=$1 order by id limit $2',[scope,2*n])).rows.map(r=>r.memo_plain);}finally{await pool.end();}
const reviews=readFileSync('.local/ratings.txt','utf8').split('\n').slice(1).map(l=>l.split('\t')[1]).filter((s):s is string=>!!s&&Array.from(norm(s)).length>=2);
const results=[run('fixture-memo',fixture.slice(0,n),fixture.slice(n)),run('nsmc-review',reviews.slice(0,n),reviews.slice(n,2*n))];
function compareT4(dataset:string,values:string[],reference:string[]){const p=profiles('mission-astra','memo',{type:'text',search:{substring:true}})[0],key=Buffer.from(hkdfSync('sha384',Buffer.alloc(32,93),Buffer.alloc(0),frame(['sealql/index/v3','global',descriptorBytes(p)]),48));const cache=new Map<string,string>();const tok=(b:Uint8Array)=>{const s=hex(b);let t=cache.get(s);if(!t){t=createHmac('sha384',key).update(frame(['value',scope,b])).digest('hex').slice(0,4);cache.set(s,t);}return t;};const tokenRows=values.map(v=>new Set(searchPieces(p,v).map(tok))),f=new Map<string,number>();for(const v of reference)for(const b of pieces(v))f.set(b,(f.get(b)??0)+1);const qs=[...f].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,128).map(x=>x[0]);let fp=0,candidateTotal=0,exactTotal=0;for(const q of qs){const token=tok(searchPieces(p,q,'contains')[0]);for(let i=0;i<n;i++){const exact=norm(values[i]).includes(q),candidate=tokenRows[i].has(token);if(candidate)candidateTotal++;if(exact)exactTotal++;if(candidate&&!exact)fp++;assert(!exact||candidate);}}return {dataset,queries:qs.length,exactPositiveMemberships:exactTotal,currentCandidateMemberships:candidateTotal,currentFalsePositiveMemberships:fp,removedMembershipPct:100*fp/candidateTotal,meaning:'exact DB predicate discloses which of these candidate memberships are false; this is not plaintext recovery rate'};}
const t4MembershipDelta=[compareT4('fixture-memo',fixture.slice(0,n),fixture.slice(n)),compareT4('nsmc-review',reviews.slice(0,n),reviews.slice(n,2*n))];
writeFileSync('bench/results/2026-09-28-mission/m1-astra-query.json',JSON.stringify({scenario:'T4 observer sees exact result sets for top reference bigram queries; query labels hidden from attacker; known-row incidence matching',notMeasured:'actual workload distribution, adaptive injection, structural extension',seed:99,results,t4MembershipDelta},null,2)+'\n');console.log(JSON.stringify({results,t4MembershipDelta}));
