// m1-fable probe: read-only look at the disposable cluster (schemas, fixture, product companion layout).
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { Pool } from 'pg';
import { assertDisposable } from '../../test/disposable.js';
assert(existsSync('.local/research/db-free.flag'), 'db-free.flag missing');
const pool = new Pool({ host: '127.0.0.1', port: 56439, user: 'sealql_test', database: 'postgres', max: 1, options: '-c default_transaction_read_only=on' });
await assertDisposable(pool); assert.equal(Number((await pool.query('show port')).rows[0].port), 56439);
const q = async (s: string, p: unknown[] = []) => (await pool.query(s, p)).rows;
console.log('schemas', (await q(`select nspname from pg_namespace where nspname not like 'pg_%' and nspname<>'information_schema' order by 1`)).map(r => r.nspname).join(' '));
console.log('tables', JSON.stringify(await q(`select schemaname||'.'||relname t, n_live_tup n, pg_size_pretty(pg_total_relation_size(relid)) sz from pg_stat_user_tables where schemaname in ('bench_realistic_100k','native_verify_main') order by 1`)));
console.log('cols', JSON.stringify(await q(`select column_name, data_type from information_schema.columns where table_schema='native_verify_main' and table_name='customers_seal_index' order by ordinal_position`)));
console.log('idx', JSON.stringify(await q(`select indexdef from pg_indexes where schemaname='native_verify_main' and tablename='customers_seal_index'`)));
console.log('scopes', JSON.stringify(await q(`select scope_id, count(*) n from bench_realistic_100k.customers group by 1`)));
console.log('companies', JSON.stringify(await q(`select company_plain, count(*) n from bench_realistic_100k.customers group by 1 order by 2 desc limit 20`)));
console.log('lens', JSON.stringify(await q(`select avg(length(memo_plain)) memo, max(length(memo_plain)) memo_max, avg(length(name_plain)) name, avg(length(address_plain)) addr, avg(length(email_plain)) email, count(distinct name_plain) dn, count(distinct memo_plain) dm, count(distinct address_plain) da, count(distinct email_plain) de, count(distinct phone_plain) dp from bench_realistic_100k.customers`)));
console.log('sample', JSON.stringify((await q(`select name_plain,company_plain,address_plain,memo_plain,email_plain,phone_plain from bench_realistic_100k.customers order by id limit 3`))));
console.log('ext', JSON.stringify(await q(`select extname, extversion from pg_extension`)));
console.log('ver', JSON.stringify(await q(`show server_version`)));
console.log('lock', existsSync('.local/research/measure.lock'));
await pool.end();
