import {readFileSync,writeFileSync,existsSync,copyFileSync} from 'node:fs';
import {OUT,median,condition,assert} from './common.js';
const r=JSON.parse(readFileSync(`${OUT}/measure.json`,'utf8'));
assert(r.complete&&r.rows.length===118&&r.errors.length===0);
const paths=['plain','old','new'],names:any={plain:'평문',old:'이전 7c14bda',new:'새 638f9c2'},fmt=(v:number)=>v.toFixed(2),esc=(v:string)=>v.replace(/\|/g,'\\|');
const groups=[['count55',r.rows.filter((x:any)=>x.group==='core'&&x.mode==='count')],['목록300 55',r.rows.filter((x:any)=>x.group==='core'&&x.mode==='list300')],['literal LIKE 재확인3',r.rows.filter((x:any)=>x.group==='literalLikeRepeat')],['일반 LIKE2',r.rows.filter((x:any)=>x.group==='generalLike')],['전체목록3',r.rows.filter((x:any)=>x.group==='wholeList')],['전체118',r.rows]] as [string,any[]][];
const lines=[`# P1 독립 검증: 평문 / 이전 제품 / 새 제품`, '',`118/118항목, 3경로 모두 평문 정답과 일치했다. 각 항목·경로의 첫 실행 1회, 예열2회, 측정7회를 포함한 총 ${118*3*10}회 호출을 검사했다. 제품 목록의 ID 순서·정규화 값뿐 아니라 원문 공백·대소문자를 포함한 여섯 칸도 매번 일치했다.`, '',`이전 제품은 7c14bda와 소스·빌드 설정 차이가 없는 적재 시점 빌드를 보존해 사용했다(파일 ${r.baselineBuildVerifiedFiles}개 SHA-256 확인). 새 제품은 638f9c2 빌드다. 두 공개 API의 extraMigrationSql이 완전히 같아 같은 10만 행 표·함수를 공유하고 각 빌드가 생성하는 SQL로 비교했다. 제품 SQL을 벤치에서 재작성하지 않았다.`, '',`측정 기간: ${r.started} ~ ${r.finished}. 동일 물리 연결, work_mem=${r.session.work_mem}, max_parallel_workers_per_gather=${r.session.gather}, 측정 락 사용. 준비 단계에서 공유 함수 재설치와 VACUUM ANALYZE를 수행했다.`, '',`첫 실행은 따로 저장했고 캐시를 비우지 않았으므로 cold 측정이 아니다. 각 조건은 예열2회 뒤 교차7회 중앙값이다. 홀수 경로 수에 맞춰 여섯 Williams 순서에서 모든 방향의 인접 경로 쌍을 두 번씩 배치했다. 일곱 번째 순서는 조건마다 순환하므로 7회 자체가 완전 균형은 아니다.`, '',`기본 55조건에는 단일 literal LIKE 3개가 이미 포함된다. 요청한 추가 LIKE3은 별도 재확인으로 표시했다. 일반 LIKE는 email의 %te%st와 %te__ 목록300이며 전체목록은 exact_common·sub_rare·exact_one이다.`, '',`## 요약`, '',`조건별 중앙값들의 산술평균·중앙값이다. 임계 초과 수는 각 조건의 중앙값 기준이며 개별 호출의 꼬리 지연이나 동시 부하를 뜻하지 않는다.`, '', '| 구간 | 지표 | 경로 | 평균 ms | 중앙값 ms | >200ms | >1초 |','|---|---|---|---:|---:|---:|---:|'];
const summary:any=[];
for(const [group,rows] of groups)for(const metric of ['sqlMs','totalMs'])for(const path of paths){const values=rows.map(x=>x.summary[path][metric]),s={group,metric,path,mean:values.reduce((a,b)=>a+b,0)/values.length,median:median(values),above200:values.filter(x=>x>200).length,above1000:values.filter(x=>x>1000).length};summary.push(s);lines.push(`| ${group} | ${metric==='sqlMs'?'SQL 왕복':'전체'} | ${names[path]} | ${fmt(s.mean)} | ${fmt(s.median)} | ${s.above200} | ${s.above1000} |`);}
lines.push('','## 이전 제품 대비 변화','','차이 = 새−이전, 배수 = 새/이전(작을수록 빠름). SQL 왕복은 클라이언트 요청부터 응답까지의 합이며 DB 서버 실행 시간만을 뜻하지 않는다. 전체 시간은 토큰 준비·전송·인증 복호화·결과 구성을 포함한다.','', '| 구간 | 지표 | 평균 차이 ms | 평균 새/이전 | 최악 악화(절대 ms) | 최악 배수 |','|---|---|---:|---:|---|---|');
for(const [group,rows] of groups)for(const metric of ['sqlMs','totalMs']){const ranked=rows.map(x=>({name:x.name,mode:x.mode,delta:x.summary.new[metric]-x.summary.old[metric],ratio:x.summary.new[metric]/x.summary.old[metric]})),worst=[...ranked].sort((a,b)=>b.delta-a.delta)[0],ratio=[...ranked].sort((a,b)=>b.ratio-a.ratio)[0],oldMean=summary.find((s:any)=>s.group===group&&s.metric===metric&&s.path==='old').mean,newMean=summary.find((s:any)=>s.group===group&&s.metric===metric&&s.path==='new').mean;lines.push(`| ${group} | ${metric==='sqlMs'?'SQL 왕복':'전체'} | ${fmt(newMean-oldMean)} | ${fmt(newMean/oldMean)}× | ${esc(worst.name)} ${worst.mode}: ${fmt(worst.delta)} | ${esc(ratio.name)} ${ratio.mode}: ${fmt(ratio.ratio)}× (${fmt(ratio.delta)}ms) |`);}
for(const metric of ['sqlMs','totalMs']){lines.push('',`## 조건별 ${metric==='sqlMs'?'SQL 왕복':'전체 API'} 시간`,'','| 조건 | 모드·구간 | 평문 ms | 이전 ms | 새 ms | 차이 ms | 새/이전 | 정답/반환 | C 한글LIKE |','|---|---|---:|---:|---:|---:|---:|---:|---|');for(const x of r.rows)lines.push(`| ${esc(x.name)} | ${x.mode}/${x.group} | ${fmt(x.summary.plain[metric])} | ${fmt(x.summary.old[metric])} | ${fmt(x.summary.new[metric])} | ${fmt(x.summary.new[metric]-x.summary.old[metric])} | ${fmt(x.summary.new[metric]/x.summary.old[metric])}× | ${x.hits}/${x.returned} | ${x.cLocaleKoreanLike?'해당':''} |`);}
lines.push('','## SQL 호출·전송·인증 복호화','','아래 수치는 실제 호출 계측 중앙값이다. 전송 행은 DB 응답 rows 합계이며 SQL 내부에서 판정한 후보 행 수와 다르다. SQL 내부 후보·판정 루프 수는 이번 측정에서 별도 계측하지 않았다. count의 반환은 정확한 정수 하나이며 표의 반환1은 응답 레코드 수를 뜻한다.','', '| 조건 | 모드·구간 | 이전 SQL/전송행/open | 새 SQL/전송행/open | 이전→새 후보 토큰 길이 |','|---|---|---|---|---|');
for(const x of r.rows){const cell=(p:string)=>{const m=x.summary[p];return `${m.sqlCalls}/${m.appRows}/${m.opens}`;};lines.push(`| ${esc(x.name)} | ${x.mode}/${x.group} | ${cell('old')} | ${cell('new')} | ${x.tokenLengths.old.join(',')||'없음'} → ${x.tokenLengths.new.join(',')||'없음'} |`);}
lines.push('','## 질의 정의','','| 조건 | 정규화 전 공개 API 조건 |','|---|---|');const seen=new Set();for(const x of r.rows)if(!seen.has(x.name)){seen.add(x.name);lines.push(`| ${esc(x.name)} | ${esc(condition(x.node))} |`);}
lines.push('','## 근거와 한계','','- [전체 반복·첫 실행·SQL·세션·정답 기록](measure.json), [요약 JSON](summary.json), [보존 빌드](baseline-build.json), [새 빌드](new-build.json), [적재 기록](load.json), [적재 보고](load-report-ko.md).','- [공개 API 측정 코드](../../../p1-verify/v-astra/run.ts), [계측](../../../p1-verify/v-astra/instrument.ts), [보고 생성](../../../p1-verify/v-astra/report.ts).','- 평문 oracle는 보호 fixture 원문에 제품 정규화를 적용한 메모리 판정이다. 시간 기준은 같은 fixture의 정규화 평문 SQL이며 매 호출마다 두 결과를 대조했다. 목록은 ID 오름차순·같은 여섯 칸을 반환한다.','- C 로캘의 한글 평문 LIKE는 전체 스캔할 수 있다. 해당 조건은 표에 표시했으며 평문 대비 속도 우위를 성능 주장으로 사용하지 않는다.','- 단일 scope 10만 행, 순차 단일 연결의 로컬 합성 fixture 실측이다. 동시 부하·운영 규모·보안 인증을 보장하지 않는다.','- 새 제품의 실제 후보 배열이 최대3임을 모든 첫 실행 SQL에서 단언했다. 이 검사는 판정 함수 전체 입력을 최대3으로 줄였다는 뜻이 아니다.','');
if(existsSync(`${OUT}/focus-zero-and-common2.json`)){
 const f=JSON.parse(readFileSync(`${OUT}/focus-zero-and-common2.json`,'utf8'));assert(f.complete&&f.errors.length===0);
 lines.push('','## 추가 확인: zero_and_common2 목록300','',`주 측정 뒤 추가 실행했다. 실제 SQL 문자열 동일: **${f.sqlIdentical}**, 실제 파라미터 동일: **${f.paramsIdentical}**. 각 경로의 SQL 문장별 EXPLAIN (ANALYZE, BUFFERS, VERBOSE)을 1회 수집하고, 예열2회 후 기존 조건과 정확히 같은 경로 순서로 7회 추가 측정했다. 원래118항목 결과는 그대로 보존했다.`, '', '| 구간 | 지표 | 평문 ms | 이전 ms | 새 ms | 차이 ms | 새/이전 |','|---|---|---:|---:|---:|---:|---:|');
 for(const [label,s] of [['주 측정',f.original],['추가7회',f.summary]] as [string,any][])for(const metric of ['sqlMs','totalMs'])lines.push(`| ${label} | ${metric==='sqlMs'?'SQL 왕복':'전체'} | ${fmt(s.plain[metric])} | ${fmt(s.old[metric])} | ${fmt(s.new[metric])} | ${fmt(s.new[metric]-s.old[metric])} | ${fmt(s.new[metric]/s.old[metric])}× |`);
 lines.push('',f.sqlIdentical&&f.paramsIdentical?'두 빌드가 같은 SQL·파라미터를 보냈으므로 이 조건의 최초 SQL 시간 차이는 P1 토큰 선택으로 달라진 질의의 퇴행을 보여주지 않는다. 같은 SQL의 왕복 측정 변동으로 분류하되, 추가7회에서도 격차가 재현되어 무작위 잡음으로 단정하지 않는다. EXPLAIN의 서버 실행 시간은 비슷했으며 왕복 격차의 원인은 이번 확인에서 밝혀지지 않았다. 전체 API 시간에는 서로 다른 빌드의 준비·처리 비용도 포함되므로 SQL 동일성만으로 그 비용까지 같다고 단정하지 않는다.':'SQL 또는 파라미터가 달라 별도 원인 확인이 필요하다. 아래 원문과 실행 계획을 근거로 판단한다.','', '| 경로/SQL | 계획 루트 | 예상/실제 행 | 실행 ms | shared hit/read |','|---|---|---:|---:|---:|');
 for(const path of ['old','new'])for(const [i,entry] of f.plans[path].entries()){const p=entry[0],n=p.Plan;lines.push(`| ${names[path]}/${i+1} | ${n['Node Type']} | ${n['Plan Rows']}/${n['Actual Rows']} | ${fmt(p['Execution Time'])} | ${n['Shared Hit Blocks']??0}/${n['Shared Read Blocks']??0} |`);}
 lines.push('','[추가7회·실제 SQL/파라미터·실행 계획 원문](focus-zero-and-common2.json), [재현 코드](../../../p1-verify/v-astra/focus.ts).','');
}
if(existsSync(`${OUT}/predecessor-diagnostic.json`)){
 const d=JSON.parse(readFileSync(`${OUT}/plan-cache-diagnostic.json`,'utf8')),p=JSON.parse(readFileSync(`${OUT}/predecessor-diagnostic.json`,'utf8'));assert(d.complete&&p.complete);
 lines.splice(4,0,'추가 원인 확인에서 zero_and_common2 목록의 최초 악화는 선행 평문 조회에 따른 shared-buffer 재읽기 효과로 확인됐다. 선행 조건을 맞추면 이전·새 제품이 각각 약45ms 또는 약18ms로 같아진다. 아래 원시 표는 보존했으며 마지막 원인 확인 절을 함께 읽어야 한다.','');
 lines.push('','## 원인 확인: prepared plan과 선행 질의 캐시 효과','', '**결론: zero_and_common2의 20 대 55ms 차이는 P1 SQL 퇴행이 아니라 선행 평문 조회가 바꾼 shared-buffer 상태와 측정 순서의 결합이었다.** 선행 질의를 같게 통제하면 두 공개 API의 시간이 같아진다. 실제 제품 호출에서도 검색 데이터가 버퍼에서 밀려난 상황은 느려질 수 있지만, 이 조건에서는 이전·새 제품 모두 같은 영향을 받았다.', '', '| 확인 항목 | 관찰 |','|---|---|', '| 드라이버 | 두 제품 모두 같은 pg Client, config 객체 + 두 번째 values 배열 + callback; rowMode=array; name 없음; 같은 custom type parser 경로 |','| prepared statement | 초기·auto7회 후·custom7회 후·종료 모두 pg_prepared_statements가 비어 있음 |', '| auto→force_custom_plan | 왕복 차이가 남음. 이름 있는 prepared statement의 generic 전환으로 설명되지 않음 |', '| 동일 SQL 직접 실행 | 제품 준비 없이 같은 SQL·파라미터를 번갈아 실행하면 두 레이블의 시간은 비슷함 |','', '| 실행 | plan_cache_mode | 이전 SQL ms | 새 SQL ms |','|---|---|---:|---:|');
 for(const mode of ['auto','force_custom_plan'])for(const [label,section] of [['공개 API·기존 순서',d.modes],['동일 SQL 직접 반복',d.direct]] as [string,any][])lines.push(`| ${label} | ${mode} | ${fmt(section[mode].summary.old.sqlMs)} | ${fmt(section[mode].summary.new.sqlMs)} |`);
 lines.push('', '선행 질의 통제는 force_custom_plan에서 각 조합 예열2회+추가7회로 실행했다. 아래 실제 API 시간은 앞서 수집한 SQL 재생이 아니라 해당 빌드의 공개 findMany 호출이다.', '', '| 바로 앞 실행 | 대상 | SQL 중앙값 ms | 전체 중앙값 ms |','|---|---|---:|---:|');
 for(const v of p.controlled)lines.push(`| ${names[v.before]} | ${names[v.target]} | ${fmt(v.summary.sqlMs)} | ${fmt(v.summary.totalMs)} |`);
 lines.push('', '각 선행 조건 뒤 EXPLAIN ANALYZE BUFFERS도 별도로 1회씩 실행했다. shared read는 PostgreSQL 공유 버퍼로 블록을 읽었다는 뜻이며 물리 디스크 읽기 횟수로 해석하지 않는다.', '', '| 바로 앞 실행 | 대상 | 서버 실행 ms | shared hit | shared read |','|---|---|---:|---:|---:|');
 for(const v of p.plans){const plan=v.plan[0];lines.push(`| ${names[v.before]} | ${names[v.path]} | ${fmt(plan['Execution Time'])} | ${plan.Plan['Shared Hit Blocks']} | ${plan.Plan['Shared Read Blocks']} |`);}
 const custom=d.customPlan[0],generic=d.genericPlan[0];
 lines.push('', '| 계획 비교 | custom (ANALYZE 포함) | GENERIC_PLAN (추정만) |','|---|---:|---:|', `| 루트 추정 행 수 | ${custom.Plan['Plan Rows']} | ${generic.Plan['Plan Rows']} |`, `| 루트 total cost | ${fmt(custom.Plan['Total Cost'])} | ${fmt(generic.Plan['Total Cost'])} |`, `| 서버 실행 ms | ${fmt(custom['Execution Time'])} | 측정 안 함 |`, '', 'generic 계획은 파라미터 값을 모르는 추정 계획으로 저장했다. 두 계획 모두 sample·quick·fallback 및 BitmapAnd 골격을 사용하지만 추정 행 수·비용은 다르다. 실제 공개 API에서 이름 있는 prepared statement를 재사용한 증거가 없고 force_custom_plan 실측도 원래 격차를 유지하므로 generic 계획 차이는 이번 원인이 아니다.', '', '기존 여섯 Williams 순서는 각 회 내부의 선행 쌍만 균형이다. 회 사이의 연결과 추가 일곱 번째 순서까지 포함한 연속 실행에서는 이 조건의 평문 직후 횟수가 이전2회·새4회가 되어, 새 제품의 7회 중앙값이 버퍼 재읽기 구간을 선택했다. 반복별 시간이 그 순서와 일치했고 선행 통제·BUFFERS로 확인했다. 따라서 최초 표의 이 조건 악화를 제품 변화로 해석하지 않는다. 다른118항목 수치와 평균은 원시 측정 그대로 보존하며, 전체 행렬의 선행 캐시 영향을 모두 재검증한 것은 아니다.', '', '[드라이버 호출·auto/custom7회·직접 SQL·generic/custom 계획](plan-cache-diagnostic.json), [선행 통제7회·BUFFERS 원문](predecessor-diagnostic.json), [plan 재현 코드](../../../p1-verify/v-astra/plan-cache-diagnostic.ts), [선행 통제 코드](../../../p1-verify/v-astra/predecessor-diagnostic.ts).','');
}
if(!existsSync(`${OUT}/load-report-ko.md`))copyFileSync(`${OUT}/report-ko.md`,`${OUT}/load-report-ko.md`);
writeFileSync(`${OUT}/summary.json`,JSON.stringify({complete:true,rows:r.rows.length,summary},null,2)+'\n');
writeFileSync(`${OUT}/report-ko.md`,lines.join('\n'));
console.log(JSON.stringify({rows:r.rows.length,summary:summary.filter((x:any)=>x.group==='전체118')}));
