import {drizzle} from 'drizzle-orm/node-postgres';
import {connect,locked,save,readFileSync,OUT,schema,scope,assert,delay} from './common.js';
import {sealed,customersSeal} from './product.js';
import {cases} from './measure.js';
import {match,plainWhere} from '../final-return/oracle.js';
import {measured} from '../final-return/instrument.js';
const result=JSON.parse(readFileSync(`${OUT}/measure.json`,'utf8')),progress=JSON.parse(readFileSync(`${OUT}/progress.json`,'utf8'));assert.equal(result.rows.length,36);assert(progress.cloneComplete);const pool=await connect(),db=drizzle(pool);
while((await pool.query('select 1 from pg_stat_activity where pid=$1',[result.pid])).rows.length)await delay(500);
try{await locked(async()=>{result.explainFinalizerPid=(await pool.query('select pg_backend_pid() pid')).rows[0].pid;for(const c of cases)for(const parallel of [2,4,8])for(const path of ['plain','product']){if(result.plans.some((p:any)=>p.scale===1000000&&p.name===c.name&&p.parallel===parallel&&p.path===path))continue;await pool.query('set max_parallel_workers_per_gather='+parallel);const out=await measured(async()=>{if(path==='product')return sealed.count(db,customersSeal,{scope,match:m=>match(c.node,m)});const params:unknown[]=[scope],where=plainWhere(c.node,params);return (await pool.query(`select count(*)::int n from ${schema}.customers_plain where scope_id=$1 and ${where}`,params)).rows[0].n;});assert.equal(out.value,result.rows.find((r:any)=>r.scale===1000000&&r.name===c.name&&r.parallel===parallel).expected);const plans=[];for(const q of out.queries)plans.push({sql:q.text,plan:(await pool.query('explain (analyze,buffers,format json) '+q.text,q.values)).rows[0]['QUERY PLAN']});result.plans.push({scale:1000000,name:c.name,parallel,path,plans});save('measure',result);}
 result.capacity=[];for(const table of ['customers','customers_seal_index','customers_plain'])result.capacity.push({table,...(await pool.query('select pg_relation_size($1)::text heap,pg_indexes_size($1)::text indexes,pg_total_relation_size($1)::text total',[schema+'.'+table])).rows[0]});assert.equal(result.plans.length,72);result.complete=true;progress.complete=true;result.finished=new Date().toISOString();save('measure',result);
 });}catch(e){result.errors.push(String(e));progress.errors.push(String(e));save('measure',result);throw e;}finally{await locked(async()=>{assert.equal(schema,'test_scale_count_million_v_astra');await pool.query(`drop schema ${schema} cascade`);assert.equal((await pool.query('select to_regnamespace($1) n',[schema])).rows[0].n,null);progress.cleaned=true;});await pool.end();progress.finished=new Date().toISOString();save('progress',progress);}
