import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import assert from 'node:assert/strict';
const dir='bench/results/2026-09-29-scale-count-million',p=JSON.parse(readFileSync(`${dir}/progress.json`,'utf8')),m=existsSync(`${dir}/measure.json`)?JSON.parse(readFileSync(`${dir}/measure.json`,'utf8')):{rows:[],plans:[],complete:false};
const n=x=>Number(x).toFixed(2),lines=['# 100만 행 개수 세기 규모 실측','','**복제 파생, 개수 세기 비용 측정 전용, 목록 복호화 측정 불가.**','',`공개 API 기준 커밋 \`${p.commit}\`. API 적재 ${p.loaded}/100000행, 100만 복제 완료 ${p.cloneComplete}, 측정 완료 ${m.complete}, 자기 스키마 정리 ${p.cleaned??false}.`,'','원본 fixture 10만 행의 6칸 원문을 공개 sealed.insert(500행×4연결)로 적재했다. 회사 exact bits=2, 나머지 기본 exact/substring 설정이다. 이후 원본 각 행에 결정적 새 ID를 붙여 부모·검색 표를 SQL로 9회 복제했다. 도장·salt·토큰·암호문을 보존했으므로 신규 행의 암호문 AAD는 신규 ID와 일치하지 않는다. 복호화·목록·보안 성질의 검증으로 사용할 수 없다. 평문 표도 같은 값과 ID로 복제했다.','', '같은 연결에서 평문/제품 × max_parallel_workers_per_gather 2/4/8의 순서를 회전했다. 첫 실행은 별도, 예열2·교차7의 지표별 중앙값이며 OS 캐시는 비우지 않았다. 모든 호출은 원본 원문의 독립 정규화 oracle 일치수 × 규모배수와 같아야 한다. count는 DB 반환1행, 인증 복호화0회를 실제 계측했다. 내부 후보 수는 실행마다 계측하지 않았으며 실행 계획의 노드 행 수와 구분한다.','', 'SQL 시간은 클라이언트 요청~응답이고 전체 시간은 준비를 포함한다. 중앙값끼리는 합산되지 않을 수 있다. † 조건의 한글 평문 LIKE는 C 로캘에서 전체 스캔 영향을 받으므로 평문 대비 배율을 성능 주장에 쓰지 않는다. 10만 대비100만 배율은 같은 값·일치비율의 규모 비교이며 독립적인 실제100만 행의 다양성을 대표하지 않는다.',''];
function table(head,rows){lines.push('| '+head.join(' | ')+' |','| '+head.map(()=>'---').join(' | ')+' |',...rows.map(row=>'| '+row.join(' | ')+' |'),'');}
lines.push('단일 scope에 100만 행을 모은 것은 이번 규모 범위의 최악 조건이다. 실제 다중 사용자 서비스에서 한 scope가 10만 행이면 scope별로 토큰이 분리되므로 판정 대상은 10만 행에 가까워질 것으로 예상한다. 다만 공유 색인·버퍼·전체 표 크기의 영향이 남아 동일 시간을 보장하지 않으며, 다중 scope와 동시 부하는 이번에 실측하지 않았다.','');
if(existsSync(`${dir}/head-recheck.json`)){const h=JSON.parse(readFileSync(`${dir}/head-recheck.json`,'utf8')),changed=h.rows.filter(r=>Math.abs(r.priorProductSqlChange)>.15||Math.abs(r.priorProductTotalChange)>.15);lines.push('## 최종 HEAD 10만 행 재검수','',`커밋 \`${h.commit}\`의 extraMigrationSql을 재설치한 공개 API 원본 적재본에서 55개 count와 LIKE 목록300 3개를 평문과 대조했다. 예열2·교차7, 병렬도2, 완료 ${h.complete}, 완료 조건 ${h.rows.length}/58. 목록은 실제 6필드 인증 복호화와 정규화 원문 일치를 확인했다.`, '',`연구 기준선은 삭제되어 다시 측정하지 않았다. 아래 연구 값과 이전 제품 값은 \`${h.priorCommit}\` [이전 세션](../2026-09-29-final-return/remeasure.json)의 측정이며 현재 세션과 다르다. 적재 salt·물리 배치·버퍼 상태도 다르므로 변화 전체를 코드 효과로 해석할 수 없다. 이전 제품 대비 SQL 또는 전체 시간 변화의 절댓값이 15%를 넘는 조건만 표시한다(${changed.length}/${h.rows.length}). 전 조건 원시는 [head-recheck.json](head-recheck.json)에 보존한다.`, '');table(['조건/모드','현재 평문 SQL','이전 연구 SQL','이전 제품 SQL','현재 제품 SQL','SQL 변화','이전/현재 제품 전체','전체 변화'],changed.map(r=>[`${r.name}/${r.mode}`,n(r.summary.plain.sqlMs),n(r.prior.research.sqlMs),n(r.prior.product.sqlMs),n(r.summary.product.sqlMs),n(100*r.priorProductSqlChange)+'%',n(r.prior.product.totalMs)+'/'+n(r.summary.product.totalMs),n(100*r.priorProductTotalChange)+'%']));}
if(m.complete){const million=m.rows.filter(r=>r.scale===1000000),base=m.rows.filter(r=>r.scale===100000),ms=million.map(r=>r.summary.product.sqlMs),ratios=million.map(r=>r.summary.product.sqlMs/base.find(b=>b.name===r.name&&b.parallel===r.parallel).summary.product.sqlMs);lines.push('## 관측 결론','',`제품 SQL 중앙값은 10만 행 ${n(Math.min(...base.map(r=>r.summary.product.sqlMs)))}–${n(Math.max(...base.map(r=>r.summary.product.sqlMs)))}ms, 100만 행 ${n(Math.min(...ms))}–${n(Math.max(...ms))}ms였다. 100만 행의 18개 조건·병렬도 조합 중 200ms 초과 ${ms.filter(x=>x>200).length}개, 1초 초과 ${ms.filter(x=>x>1000).length}개다. 같은 조건·설정에서 10배 행 수의 제품 SQL 시간은 ${n(Math.min(...ratios))}–${n(Math.max(...ratios))}배였다.`,'',`서버 max_parallel_workers=${m.settings.max_parallel_workers}, max_worker_processes=${m.settings.max_worker_processes}, work_mem=${m.settings.work_mem}. 실제 실행 계획의 기동 worker 수는 아래 별도 표에 있다.`, '');}
if(m.complete){lines.push('100만 행 이메일 끝·서비스 상담은 별도 실행 계획에서 병렬 worker가 없었고 설정2/4/8에서도 약5.5–5.8초·4.0초였다. 메모 서비스는 설정8에서도 계획/기동 worker가4개였다. 병렬도 설정 증가만으로 모든 흔한 count를1초 아래로 낮추지는 못했다.','');table(['조건','10만 설정2 ms','100만 설정2 ms','100만 설정4 ms','100만 설정8 ms'],m.cases.map(c=>[c.name,...[[100000,2],[1000000,2],[1000000,4],[1000000,8]].map(([scale,p])=>n(m.rows.find(r=>r.name===c.name&&r.scale===scale&&r.parallel===p).summary.product.sqlMs))]));}
lines.push('## 적재·복제','', '근거: [progress.json](progress.json), [schema.json](schema.json), [clone-indexes.json](clone-indexes.json).','');
if(p.ingestCommit)lines.push(`초기 공개 API 적재는 \`${p.ingestCommit}\`에서 시작하고 최종 \`${p.commit}\` 빌드로 마쳤다. 두 커밋의 제품 소스 차이는 JOIN 콜백 타입 선언·주석뿐이며 저장 형식과 런타임 쓰기 경로는 동일하다. 전체 조회는 최종 커밋 함수 재설치 후 측정했다.`, '');
table(['항목','값'],[['API 활성 적재 초',n((p.loadActiveMs??0)/1000)],['API 경과 초(락 대기 포함)',n((p.loadElapsedMs??0)/1000)],['API 활성 행/초',n(p.rowsPerSecond??0)],['복제·색인·VACUUM 초',p.cloneComplete?n(p.cloneElapsedMs/1000):'진행 중'],['원문 왕복 필드',p.baseRawRoundtrip??0]]);
if(p.resumedAt)lines.push('적재 중 상태 알림을 끄기 위해 프로세스를 재개했다. 적재 시간·행/초는 완료 예상용 참고값이며 마지막 진행 저장 이후 커밋된 배치의 시간은 빠질 수 있다. 조회 시간 측정은 재개 이후 완성된 데이터에서 처음부터 수행했다.','');
lines.push('측정 구간과 적재 배치는 공통 락으로 순서화했다. 복제 시 자기 표의 비고유 보조 색인을 잠시 제거하고 동일 정의로 다시 만든 뒤 VACUUM ANALYZE했다. 보호 표는 읽기만 했다.','');
lines.push('## SQL 요청~응답 (ms)','','근거: [measure.json](measure.json). 설정값은 실제 기동 worker 수를 보장하지 않는다.','');
table(['조건','행 수','일치 수/비율','병렬도 설정','평문','제품','제품 >200ms','제품 >1초'],m.rows.map(r=>[r.name+(r.cLocaleKoreanLike?' †':''),r.scale,`${r.expected}/${n(100*r.matchRatio)}%`,r.parallel,n(r.summary.plain.sqlMs),n(r.summary.product.sqlMs),r.summary.product.sqlMs>200?'예':'아니오',r.summary.product.sqlMs>1000?'예':'아니오']));
lines.push('## 전체 시간과 비용 분리 (ms)','','근거: [measure.json](measure.json).','');
table(['조건/행 수/병렬도','평문 전체','제품 전체','제품 pre/between/post','첫 제품 SQL/전체','SQL 횟수','DB 반환','인증 복호화'],m.rows.map(r=>{const a=r.summary.product,f=r.first.product;return [`${r.name}/${r.scale}/${r.parallel}`,n(r.summary.plain.totalMs),n(a.totalMs),[a.preMs,a.betweenMs,a.postMs].map(n).join('/'),n(f.sqlMs)+'/'+n(f.totalMs),a.sqlCalls,a.appRows,a.opens];}));
lines.push('## 10만 → 100만 규모 변화','','실측이 모두 완료된 동일 조건끼리만 비교한다.','');
table(['조건','병렬도','10만 제품 SQL','100만 제품 SQL','SQL 배율','전체 배율'],m.rows.filter(r=>r.scale===1000000).map(r=>{const b=m.rows.find(b=>b.scale===100000&&b.name===r.name&&b.parallel===r.parallel);return [r.name,r.parallel,n(b.summary.product.sqlMs),n(r.summary.product.sqlMs),n(r.summary.product.sqlMs/b.summary.product.sqlMs)+'×',n(r.summary.product.totalMs/b.summary.product.totalMs)+'×'];}));
function walk(node,out=[]){out.push(node);for(const child of node.Plans??[])walk(child,out);return out;}
lines.push('## 실행 계획의 병렬 작업과 버퍼','','EXPLAIN ANALYZE BUFFERS는 교차 측정 후 별도1회다. 내부 노드 시간은 서로 포함되므로 합산하지 않는다.','');
if(m.explainFinalizerPid)lines.push('실행 중 추가 서비스 흐름 측정이 취소되어 count 반복 완료 후 남은 EXPLAIN만 별도 연결에서 마무리했다. 10만·100만 count 중앙값은 모두 원래 동일 연결의 측정값이며, EXPLAIN용 질의 준비 호출은 중앙값에 포함하지 않았다.','');
table(['조건/행 수/설정','경로','서버 실행 ms','worker 계획/실제','shared hit/read blocks','가장 많은 스캔 실제행×loop'],m.plans.map(r=>{const all=r.plans.flatMap(q=>q.plan),nodes=all.flatMap(x=>walk(x.Plan)),g=nodes.filter(x=>x['Workers Planned']!==undefined),scan=nodes.filter(x=>x['Node Type'].includes('Scan')).sort((a,b)=>(b['Actual Rows']??0)*(b['Actual Loops']??1)-(a['Actual Rows']??0)*(a['Actual Loops']??1))[0];return [`${r.name}/${r.scale}/${r.parallel}`,r.path,n(all.reduce((s,x)=>s+x['Execution Time'],0)),g.map(x=>`${x['Workers Planned']}/${x['Workers Launched']}`).join(', ')||'병렬 없음',all.map(x=>`${x.Plan['Shared Hit Blocks']??0}/${x.Plan['Shared Read Blocks']??0}`).join(', '),scan?`${scan['Node Type']} ${scan['Actual Rows']}×${scan['Actual Loops']}`:'—'];}));
if(m.capacity){lines.push('## 최종 관계 용량','','정리 전 실제 측정, MiB=2^20 bytes.','');table(['표','heap MiB','index MiB','전체 MiB'],m.capacity.map(t=>[t.table,n(t.heap/1048576),n(t.indexes/1048576),n(t.total/1048576)]));}
if(m.cases){lines.push('## 조건 정의','');table(['조건','식'],m.cases.map(c=>[c.name,JSON.stringify(c.node)]));}
lines.push(`오류: ${[...(p.errors??[]),...(m.errors??[])].join('; ')||'없음'}.`,'','로컬 합성 fixture를 복제한 결과이며 운영 보장·보안 인증이 아니다. 제품 코드는 변경하지 않았다.','');
writeFileSync(`${dir}/report-ko.md`,lines.join('\n'));
if(m.complete){assert.equal(m.rows.length,36);assert.equal(m.plans.length,72);assert.deepEqual(m.errors,[]);for(const r of m.rows){assert.equal(r.expected,r.expectedBase*r.scale/100000);for(const path of ['plain','product']){assert.equal(r.runs[path].length,7);for(const run of r.runs[path]){assert.equal(run.opens,0);assert.equal(run.appRows,1);}}}const h=JSON.parse(readFileSync(`${dir}/head-recheck.json`,'utf8'));assert(h.complete);assert.equal(h.rows.length,58);assert.equal(p.cleaned,true);writeFileSync(`${dir}/artifact-check.json`,JSON.stringify({passed:true,rows:36,plans:72,headRecheck:58,cleaned:p.cleaned,commit:p.commit},null,2)+'\n');}
console.log(JSON.stringify({complete:m.complete,rows:m.rows.length,cleaned:p.cleaned??false}));
