import {readFileSync,existsSync,writeFileSync} from 'node:fs';
const out='bench/results/2026-09-28-count-test';
const get=(n:string)=>existsSync(`${out}/t-astra-${n}.json`)?JSON.parse(readFileSync(`${out}/t-astra-${n}.json`,'utf8')):null;
const m=get('measure'),l=get('load'),w=get('write'),edge=get('edge'),memory=get('memory'),plan=get('plan'),cleanup=get('cleanup');
const f=(x:any)=>typeof x==='number'?x.toFixed(2):'미측정';
const exact=m?.cases?.find((x:any)=>x.name==='exact'),find200=m?.cases?.find((x:any)=>x.name==='find200'),join20=m?.cases?.find((x:any)=>x.name==='join20');
const lines=['# 10만 단독 A 실용 검증 — astra','',
'실패·미검증을 먼저 기록한다. 정식 API 통합·운영 환경 성능·누출 안전성은 이번 검증 범위가 아니다.','',
...(memory?[`- **실패 — K=8 창 결합의 일반 정확성**: 실제 ${memory.sourceChars}자 원문에 없는 ${memory.queryChars}자 검색어가 실제 제품 후보와 A 태그를 모두 통과한다. 더 짧은 ${memory.shorterThanSource?.chars}자 검색어도 같은 반례여서 원문 길이 상한만 더해도 해결되지 않는다. 고유 8자 창 ${memory.uniqueKWindows}개가 모두 존재하는 반복 반례이며 해시 충돌이 아니다. 메모리 검증 완료, DB 전체 count는 아래에 기록한다.`]:[]),
...(edge?.long??[]).filter((x:any)=>!x.DBExact).map((x:any)=>`- **DB 실측 불일치** ${x.normalizedChars}자 검색어: 평문 ${x.plain}, 현재 제품 ${x.product}, A ${x.A}. 검색어 전문: ${x.term}`),
...(edge?.failures??[]).map((x:any)=>`- **사용성 실행 실패** ${x.split('\n')[0]}`),
...(exact?[`- **실패 — 평문 SQL 약 2배 목표**: 정확 일치에서 평문 ${f(exact.summary.plain.dbMs)}ms, A ${f(exact.summary.A.dbMs)}ms로 ${f(exact.summary.A.dbMs/exact.summary.plain.dbMs)}배다. 이 조건은 equality이므로 한글 LIKE의 C 로캘 예외를 적용하지 않는다.`]:[]),
...(find200?[`- **퇴행 — 200건 조회**: 현재 제품 ${f(find200.summary.product.totalMs)}ms, A ${f(find200.summary.A.totalMs)}ms. count 개선을 모든 조회 개선으로 일반화할 수 없다.`]:[]),
...(join20?[`- **퇴행 — JOIN 20건**: 현재 제품 ${f(join20.summary.product.totalMs)}ms, A ${f(join20.summary.A.totalMs)}ms로 ${f(join20.summary.A.totalMs/join20.summary.product.totalMs)}배 느리다. EXPLAIN 구조와 판단을 아래에 기록했다.`]:[]),
...(m?.failures??[]).map((x:any)=>`- **실패** ${x.case}: ${x.error.split('\n')[0]}`),
`- 완료 질의: ${m?.cases?.length??0}/19; 쓰기 측정: ${w?'완료':'미완료'}; 사용성·긴 검색어: ${edge?'별도 JSON 참조':'미완료'}.`,
'',
'A는 기존 제품의 16비트 후보 GIN/B-tree와 암호문을 그대로 복제하고, 행·필드별 16바이트 난수 salt 및 64비트 SHA-256 판정 태그를 추가한 연구 시제품이다. memo/company 두 필드에 길이 2~8 부분문자열·접두·접미와 전체 정확 일치 태그를 저장한다. 8자를 넘는 질의는 8자 창들의 존재를 AND하므로 순서·횟수·연속성을 일반적으로 보장하지 않는다.',
'',
'기존 native_verify_main 및 bench_realistic_100k는 읽기만 했다. 고객/티켓 각각 100,000행, 새 research_t_astra에서 실행했다. 조회는 6개 필드 전체를 반환하고 ID 순서 및 모든 투영값을 매 회 평문과 대조한다. 첫 측정 별도, 예열 2회 후 순서 교차 7회의 지표별 중앙값(ms)이며 지표별 중앙값은 합산되지 않을 수 있다. SQL 시간은 왕복 시간이다. C 로캘 한글 LIKE이므로 평문 대비 배율을 성능 결론에 쓰지 않는다.',
'',
'| 조회 방식 | 조건 전문 | 대상 행 | 실제 일치 | 결과 행 / 스칼라 값 | DB 후보 전체 | 경로 | SQL 호출 | 평문 SQL/합계 ms | 암호 전처리 ms | 암호 DB ms | SQL 사이 ms | 후처리 ms | 합계 ms | 앱 수신 행 | 인증 복호화 필드 |',
'|---|---|---:|---:|---:|---:|---|---:|---|---:|---:|---:|---:|---:|---:|---:|'];
for(const c of m?.cases??[])for(const p of ['product','A']){const s=c.summary[p],plain=c.summary.plain;lines.push(`| ${c.mode}${c.limit?' '+c.limit:''} | ${c.condition} | ${c.targetRows.toLocaleString()} | ${c.actualMatches.toLocaleString()} | ${c.resultRows}${c.resultValue!==undefined?' / '+c.resultValue:''} | ${c.dbCandidates} | ${p==='A'?'A':'현재 제품'} | ${s.sqlCalls} | ${f(plain.dbMs)}/${f(plain.totalMs)} | ${f(s.preMs)} | ${f(s.dbMs)} | ${f(s.betweenSqlMs)} | ${f(s.postMs)} | ${f(s.totalMs)} | ${s.rowsToApp} | ${s.openCount} |`);}
lines.push('','DB 후보 전체는 LIMIT 없는 후보 조건의 별도 COUNT로 잰 논리적 후보 집합이며 실제 plan이 읽은 tuple 수와 다르다. 앱 수신 행은 SQL 결과 행 합계이며 count(*)는 1행이다. count/SUM 결과 수 1은 스칼라 결과 행이며 일치 행 수와 구분했다. JOIN은 티켓 100,000과 고객 100,000을 customer_id로 연결하고 티켓을 반환 단위로 삼는다. 제품 JOIN count는 search로 검증된 ID를 모두 받아 길이를 계산한 조합이며 단일-table count API와 구분한다. SUM은 ticket.memo_plain의 char_length를 미리 저장한 평문 amount를 더한다; 제품은 암호 조건 검증 후 ID로 SUM하여 두 단계이며 A는 DB 한 번에 SUM한다.','');
if(l?.storage){const size=(n:string)=>Number(l.storage.find((x:any)=>x.relname===n)?.total??0);lines.push('| 대상 | 현재 부모+인덱스 bytes | 추가 태그 bytes | 합계/현재 | 태그 적재 ms/행 |','|---|---:|---:|---:|---:|');for(const t of ['customers','tickets']){const p=size(t)+size(t+'_seal_index'),a=size(t+'_tags');lines.push(`| ${t} | ${p} | ${a} | ${f((p+a)/p)}× | ${f(l[t]?.tagMsPerRow)} |`);}lines.push('','저장은 pg_total_relation_size 합계이며 TOAST·인덱스를 포함한다. 현재 제품은 6개 암호 필드, 추가 태그는 2개 필드이므로 6개 필드 모두 확장한 저장 배율로 해석하면 안 된다. 태그 적재는 인코딩+DB 삽입의 단일 배치 실행으로 전체 관리형 쓰기 성능과 구분한다.','');}
if(w){lines.push('| 관리형 삽입 | 20행 배치 전체 ms | ms/행 | SQL 호출 |','|---|---:|---:|---:|');for(const p of ['product','A']){const s=w.summary[p];lines.push(`| ${p} | ${f(s.totalMs)} | ${f(s.msPerRow)} | ${s.sqlCalls} |`);}lines.push('','원본에서 가져온 동일 20행을 연구 스키마에서 삭제 후 재삽입하고 매 회 커밋했다. 준비용 삭제는 측정 밖, BEGIN·암호화·후보 인덱스·내부 savepoint·A 태그·COMMIT은 측정 안이다. 제품 기준 경로에서 제거된 A 태그는 측정 밖에서 복구했다. 새 합성 행은 만들지 않았다.','');}
if(edge){lines.push('| 사용성 검사 | 평문 count | A count | 현재 제품 count | 결과 |','|---|---:|---:|---:|---|');for(const r of edge.results)lines.push(`| ${r.name} | ${r.plain??r.after?.plain??'—'} | ${r.A??r.after?.A??'—'} | ${r.product??r.after?.product??'—'} | ${r.pass?'일치':'실패'} |`);if(edge.concurrency)lines.push('',`동시 쓰기 ${edge.concurrency.writers}개, 서로 다른 행 갱신 ${edge.concurrency.disjointUpdates}회 및 공통 행 갱신 ${edge.concurrency.sharedRowUpdates}회; ${edge.concurrency.sameSnapshotReads}회의 repeatable-read 스냅샷에서 A와 평문 count가 같았다. 코디네이터의 명시적 락 예외 지시로 다른 적재와 병행한 정확성 검사이므로 시간 수치를 제외했다.`, '삭제는 동일 트랜잭션 안에서 count와 태그/인덱스 FK cascade를 확인한 뒤 롤백했다. 부분 수정·동시 갱신은 커밋 후 검사하고 원본 fixture 값으로 복구했다. 앱 편의 API에 A를 통합한 제품 구현은 아니다.','');}
if(plan)lines.push('EXPLAIN은 코디네이터 지시에 따라 ANALYZE 없는 계획 구조만 수집했다. JOIN 20 계획은 `Limit → Sort → Nested Loop/Gather → Hash Join`이며 tickets와 customers_tags의 Seq Scan 및 태그 판정이 Sort 아래에 있다. 따라서 ORDER BY와 LIMIT이 판정·JOIN 뒤에 놓이는 구조가 확인된다; 별도 측정에서 일치한 21,182행은 EXPLAIN의 실제 처리 행 수가 아니다. 20건만 필요해도 Sort 입력을 먼저 구성하는 계획이 큰 퇴행의 원인으로 판단된다.','', '정확 일치 count도 customers_tags Seq Scan 후 customers_seal_index 조회였고, 희귀/보통 contains count는 GIN Bitmap Scan 후 태그 Index Scan이었다. 현재 SQL은 모든 경로에서 GIN 후보 선별을 먼저 실행하도록 강제하지 않는다. 따라서 이 수치는 해당 시제품 SQL·배치의 결과이며, A 개념의 최적 성능 하한이 아니다. find200은 tags Index Scan과 Gather Merge를 선택해 find20과 계획이 달랐다. 개선된 SQL의 성능은 측정하지 않았다.','');
lines.push('| 가설 | 실험 | 결과 수치 | 판정: 확인됨/미검증/실패 |','|---|---|---|---|',`| 지정한 조건에서 DB count가 평문과 일치 | exact/contains/starts/ends/AND/OR | 완료 ${m?.cases?.filter((x:any)=>x.mode==='count').length??0}개 count 케이스, 각 경로 10회 대조 | ${m?.failures?.length?'실패':m?.finished?'확인됨':'미검증'} |`,`| 조회·JOIN·SUM의 결과가 보존 | ID 순서/6필드값/스칼라 대조 | 완료 ${m?.cases?.filter((x:any)=>x.mode!=='count').length??0}개 | ${m?.cases?.filter((x:any)=>x.mode!=='count').length===7?'확인됨':'미검증'} |`,`| 긴 검색어도 정확 | K=8 창의 순서·중복 반례 | 메모리 반례 ${memory?2:0}개, DB 불일치 ${edge?.long?.filter((x:any)=>!x.DBExact).length??0}개 | ${memory?'실패':'미검증'} |`,`| 부분 수정·삭제·동시 쓰기·롤백 보존 | 관리형 쓰기와 태그를 같은 트랜잭션으로 갱신 | 성공 검사 ${edge?.results?.filter((x:any)=>x.pass).length??0}개, 동시 writer ${edge?.concurrency?.writers??0}개 | ${edge?.failures?.length?'실패':edge?.finished?'확인됨':'미검증'} |`,`| A 추가 쓰기·저장 비용을 수치화 | 같은 원본 20행 삽입 및 relation size | 삽입 중앙값/실제 저장 bytes는 위 표 참조 | ${w&&l?.storage?'확인됨':'미검증'} |`,'',
'결론 1. 지정 조건에서 A는 count/SUM의 전체 시간을 줄였지만 JOIN20은 12.06→444.09ms로 퇴행했고, 정확 일치 SQL의 평문 약 2배 목표도 실패했다.',
`결론 2. 부분 수정·삭제·8개 동시 쓰기·롤백은 일치했고 2필드 태그 추가 저장은 약 1.36배다; 관리형 쓰기는 ${w?`${f(w.summary.product.msPerRow)}→${f(w.summary.A.msPerRow)}ms/행, ${f(w.summary.A.msPerRow/w.summary.product.msPerRow)}배였다`:'락 대기로 미검증이다'}.`,
'결론 3. 45/108자 부분검색에서 0건을 2,440건으로 잘못 세므로 K=8 창 결합을 무제한 정확 count로 채택할 수 없다; 로컬 합성 fixture 결과이며 운영 보장·보안 인증이 아니다.',
'',`정리: ${cleanup?'연구 스키마를 삭제했고 보호 대상 기존 관계가 그대로 존재함을 확인했다':'연구 스키마는 후속 검사·정리 대기 중이다'}. 기존 src·테스트·문서 수정 및 커밋은 하지 않았다.`,
'',`근거: t-astra-load.json, t-astra-measure.json, t-astra-write.json, t-astra-edge.json, t-astra-plan.json, t-astra-memory.json 및 bench/research-test/t-astra-*.ts.`);
writeFileSync(`${out}/t-astra-report-ko.md`,lines.join('\n')+'\n');console.log(`${out}/t-astra-report-ko.md`);
