/** Reviewed adaptation of the delegated draft: real product GIN/managed writes, no schema reload or synthetic data. */
import assert from 'node:assert/strict';
import {eq} from 'drizzle-orm';
import {drizzle} from 'drizzle-orm/node-postgres';
import {S,pool,db,scope,sealed,customers,lock,unlock,save,encodeField,norm,match,candidateWhere,verifyWhere,type Tree} from './t-astra-common.js';
const report:any={started:new Date().toISOString(),results:[],long:[],failures:[],syntheticRows:0};
const leaf=(f:string,v:string):Tree=>({field:f,op:'contains',value:v});
async function counts(tree:Tree,client:any=pool,productDb:any=db,withProduct=true){assert('field'in tree);const ps:any[]=[scope],pre=await candidateWhere(tree,'customers',ps),ver=verifyWhere(tree,'customers',ps);const a=Number((await client.query(`select count(*)::int n from ${S}.customers_seal_index i join ${S}.customers_tags j on j.id=i.row_id where i.scope_id=$1 and ${pre} and ${ver}`,ps)).rows[0].n);const plain=Number((await client.query(`select count(*)::int n from ${S}.customers_plain where position($1 in ${tree.field}_norm)>0`,[norm(tree.value)])).rows[0].n);const product=withProduct?await sealed.count(productDb,customers.seal,{scope,match:(m:any)=>match(tree,m)} as any):undefined;return {plain,A:a,...(withProduct?{product}: {})};}
async function check(name:string,tree=leaf('memo','서비스')){const got=await counts(tree);assert.equal(got.A,got.plain,name);assert.equal(got.product,got.plain,name);report.results.push({name,...got,pass:true});save('edge',report);console.log(name,got);}
async function transaction(fn:(tx:any,client:any)=>Promise<any>){const client=await pool.connect();try{return await drizzle(client).transaction(tx=>fn(tx,client));}finally{client.release();}}
async function patch(tx:any,client:any,id:string,field:string,value:string){await sealed.update(tx,customers.seal,{id,scopeId:scope},{[field]:value} as any);const e=encodeField('customers',field,value);await client.query(`update ${S}.customers_tags set salt_${field}=decode($1,'hex'),jt_${field}=$2::bigint[],jx_${field}=$3::bigint where id=$4`,[e.salt,e.jt,e.jx,id]);await client.query(`update ${S}.customers_plain set ${field}_plain=$1,${field}_norm=$2${field==='memo'?',amount=char_length($1)':''} where id=$3`,[value,norm(value),id]);}
const rollback=new Error('intentional rollback');
let originals:any[]=[];
try{await lock();assert.equal((await pool.query(`select count(*)::int n from ${S}.customers`)).rows[0].n,100000);originals=(await pool.query(`select id,memo_plain,company_plain from ${S}.customers_plain order by id limit 81`)).rows;
await check('baseline');
const donor=(await pool.query(`select memo_plain,company_plain from ${S}.customers_plain where position('서비스' in memo_norm)>0 and company_norm<>'서울서비스담당' order by id limit 1`)).rows[0];
const untouchedBefore=(await pool.query(`select p.company_ct,encode(j.salt_company,'hex') salt,j.jt_company,j.jx_company from ${S}.customers p join ${S}.customers_tags j on j.id=p.id where p.id=$1`,[originals[0].id])).rows[0];
await transaction((tx,c)=>patch(tx,c,originals[0].id,'memo',donor.memo_plain));await check('one-field-update');await check('one-field-update-other-count',leaf('company','담당'));
const untouchedAfter=(await pool.query(`select p.company_ct,encode(j.salt_company,'hex') salt,j.jt_company,j.jx_company from ${S}.customers p join ${S}.customers_tags j on j.id=p.id where p.id=$1`,[originals[0].id])).rows[0];assert.deepEqual(untouchedAfter,untouchedBefore);report.results.push({name:'untouched-company-bytes',pass:true});
try{await transaction(async(tx,c)=>{await tx.delete(customers.table).where(eq(customers.table.id,originals[1].id));await c.query(`delete from ${S}.customers_plain where id=$1`,[originals[1].id]);const got=await counts(leaf('memo','서비스'),c,tx);assert.equal(got.A,got.plain);assert.equal(got.product,got.plain);const cascade=(await c.query(`select (select count(*) from ${S}.customers_tags where id=$1)::int tags,(select count(*) from ${S}.customers_seal_index where row_id=$1)::int idx`,[originals[1].id])).rows[0];assert.deepEqual(cascade,{tags:0,idx:0});report.results.push({name:'delete-cascade',...got,cascade,pass:true});throw rollback;});}catch(e){if(e!==rollback)throw e;}
await check('delete-rollback');
let running=true;const snapshots:any[]=[];const reader=(async()=>{while(running){const c=await pool.connect();try{await c.query('begin isolation level repeatable read read only');const got=await counts(leaf('memo','서비스'),c,undefined,false);assert.equal(got.A,got.plain,'same-snapshot reader');snapshots.push(got);await c.query('rollback');}finally{c.release();}await new Promise(r=>setTimeout(r,5));}})();
const start=performance.now();try{await Promise.all(Array.from({length:8},(_,w)=>transaction(async(tx,c)=>{for(let k=0;k<10;k++){const row=originals[1+w*10+k];await patch(tx,c,row.id,'memo',donor.memo_plain);}await patch(tx,c,originals[0].id,w%2?'company':'memo',w%2?originals[40+w].company_plain:originals[2+w].memo_plain);})));}finally{running=false;await reader;}
report.concurrency={writers:8,disjointUpdates:80,sharedRowUpdates:8,timingExcluded:true,sameSnapshotReads:snapshots.length,snapshots};await check('after-eight-writers');await check('after-eight-writers-company',leaf('company','담당'));
const before=await counts(leaf('memo','서비스'));try{await transaction(async(tx,c)=>{await patch(tx,c,originals[0].id,'memo',originals[0].memo_plain);throw rollback;});}catch(e){if(e!==rollback)throw e;}const after=await counts(leaf('memo','서비스'));assert.deepEqual(after,before);report.results.push({name:'explicit-rollback',before,after,pass:true});
await transaction(async(tx,c)=>{for(const r of originals){await patch(tx,c,r.id,'memo',r.memo_plain);await patch(tx,c,r.id,'company',r.company_plain);}});await check('restored-100k');
const terms=['상세 안내와 확인 내용 상세 안내와','상세안내와확인내용'.repeat(5),'상세안내와확인내용'.repeat(12)];
for(const term of terms){const got=await counts(leaf('memo',term));assert.equal(got.product,got.plain);report.long.push({term,normalizedChars:Array.from(norm(term)).length,...got,DBExact:got.A===got.plain});console.log('long',JSON.stringify(report.long.at(-1)));}
report.finished=new Date().toISOString();save('edge',report);
}catch(e:any){report.failures.push(e.stack);save('edge',report);throw e;}finally{unlock();await pool.end();}
