import assert from 'node:assert/strict';
import {S,pool,scope,fields,tagFields,lock,unlock,putTags,save} from './t-astra-common.js';
const result:any={started:new Date().toISOString(),K:8,tagBits:64,tagFields,sourceRows:100000};
try{await lock();assert.equal((await pool.query('select 1 from pg_namespace where nspname=$1',[S])).rowCount,0,'existing own schema; inspect before resume');await pool.query(`create schema ${S}`);
for(const table of ['customers','tickets']){const start=performance.now();for(const name of [table,table+'_seal_index']){await pool.query(`create table ${S}.${name}(like native_verify_main.${name} including all)`);await pool.query(`insert into ${S}.${name} select * from native_verify_main.${name} where scope_id=$1`,[scope]);}await pool.query(`alter table ${S}.${table}_seal_index add foreign key(row_id) references ${S}.${table}(id) on delete cascade`);
await pool.query(`create table ${S}.${table}_plain as select id,scope_id${table==='tickets'?',customer_id':''},${fields.flatMap(f=>[`${f}_plain`,`${f}_norm`]).join(',')},char_length(memo_plain)::bigint amount from bench_realistic_100k.${table} where scope_id=$1`,[scope]);await pool.query(`alter table ${S}.${table}_plain add primary key(id)`);await pool.query(`create index on ${S}.${table}_plain(company_norm)`);
await pool.query(`create table ${S}.${table}_tags(id uuid primary key references ${S}.${table}(id) on delete cascade,${tagFields.flatMap(f=>[`salt_${f} bytea not null`,`jt_${f} bigint[] not null`,`jx_${f} bigint not null`]).join(',')})`);
const rows=(await pool.query(`select id,memo_plain,company_plain from ${S}.${table}_plain order by id`)).rows;assert.equal(rows.length,100000);let encodeInsertMs=0;for(let i=0;i<rows.length;i+=500){const t=performance.now();await putTags(pool,table,rows.slice(i,i+500));encodeInsertMs+=performance.now()-t;if(i%10000===0)console.log(table,i,Math.round(encodeInsertMs));}for(const name of [table,table+'_seal_index',table+'_plain',table+'_tags'])await pool.query(`analyze ${S}.${name}`);result[table]={loadMs:performance.now()-start,encodeInsertMs,tagMsPerRow:encodeInsertMs/rows.length};save('load',result);}
result.storage=(await pool.query(`select relname,pg_relation_size(relid)::text heap,pg_indexes_size(relid)::text indexes,pg_total_relation_size(relid)::text total from pg_stat_user_tables where schemaname=$1 order by relname`,[S])).rows;result.finished=new Date().toISOString();save('load',result);console.log(JSON.stringify(result));}finally{unlock();await pool.end();}
