import {readFileSync,writeFileSync,existsSync,mkdirSync} from 'node:fs';
const OUT='bench/results/2026-09-29-r9-verify';
const read=n=>existsSync(`${OUT}/${n}.json`)?JSON.parse(readFileSync(`${OUT}/${n}.json`,'utf8')):null;
const load=read('load'),measure=read('measure'),writes=read('writes'),capacity=read('capacity'),ticket=read('ticket-load'),join=read('join'),install=read('install');
const revision=read('revision');
const rows=measure?.rows??[],cases=read('cases')??[],baseCases=JSON.parse(readFileSync('bench/results/2026-09-29-task4/cases.json','utf8'));
const reference=readFileSync('.local/research/task4-full-table.md','utf8').split(/\r?\n/).filter(l=>/^\|\s*\d+\s*\|/.test(l)).map(l=>l.split('|').slice(1,-1).map(s=>s.trim()));
const f=n=>typeof n==='number'?n.toFixed(3):'미측정';const mb=n=>f(n/1024/1024);const safe=s=>String(s).replaceAll('|','\\|').replaceAll('\n',' ');
const ref=(name,mode)=>{const i=baseCases.findIndex(c=>c.name===name),r=reference[i];return !r||mode==='listAll'?['—','—']:mode==='count'?[r[4],r[5]]:[r[7],r[8]];};
const finish=Boolean(load?.complete&&measure?.complete&&writes?.complete&&capacity?.complete&&(join?.complete||ticket?.limitReached)&&(!revision||(measure?.commit===revision.commit&&join?.commit===revision.commit)));
let md=`# R9 제품 API 독립 검수\n\n상태: ${finish?'완료':'진행 중 또는 일부 미측정'}. 조회 ${rows.length}/115 조건·작업, 쓰기 ${writes?.complete?'완료':'미완료'}, 용량 ${capacity?.complete?'완료':'미완료'}, JOIN ${join?.complete?'완료':ticket?.limitReached?'20분 적재 제한으로 미측정':'미완료'}. DB는 지정 일회용 클러스터만 사용했으며 보호 스키마·연구 표 수정 및 커밋은 하지 않았다.\n\n## 대상과 검증 방법\n\n고객 원문 100,000행의 공백·대소문자를 보존해 공개 \`sealed.insert\`로 새 \`test_r9_verify_main\`에 적재했다. 원문 600,000필드를 독립 정규화한 결과와 \`research_u.customers_plain\`의 차이는 ${load?.normalizedBaselineMismatches??'미확인'}개다. 적재 ${load?.loaded??0}행, ${f(load?.elapsedMs)}ms; 원문 복호화 표본 ${load?.rawSampleRoundtrip??0}행이 모든 6칸에서 그대로 일치했다. 회사명 exact bits=2, 나머지 exact 기본16, 여섯 칸 substring wordBoundary=true, skipGrams 기본값이다. 스키마는 공개 Drizzle 정의에서 drizzle-kit으로 생성했고 extraMigrationSql을 설치했다.\n\n원문 SHA-256: \`${load?.sourceHash??'미확인'}\`. 초기 적재 기준 a15f85a; 최종 조회 빌드/함수 설치 정보: ${install?`${install.commit}, ${install.at}`:'아직 기록되지 않음'}. 적재 ${load?.started??'—'} ~ ${load?.finished??'진행 중'}, 조회 ${measure?.started??'—'} ~ ${measure?.finished??'진행 중'}. 물리 행 정렬·인덱스 통계는 catalog 원자료로 확인한다.\n\n각 조건은 첫 실행 1회 별도, 예열 2회, 두 경로 순서를 번갈아 7회 실행해 지표별 중앙값을 기록했다. 매 실행 count 또는 ID 순서와 정규화 6칸을 **원문에서 계산한 oracle**과 대조했다. count는 1 SQL·0 복호화, 목록은 반환 1행당 6필드 인증 복호화를 단언했다. 전체 목록은 exact_common / sub_rare / exact_one 3개이며 limit를 생략했다. SQL은 클라이언트 요청~응답 누적 시간이다. 비교용 출력 정규화와 assert는 계측 밖이다.\n\nlike 3개는 실제 첫 고객 email에서 만들었고, respectWords는 원문 공백을 유지한 \"서비스 상담\"이다. respectWords 평문 시간은 해당 fixture에서만 compact 조건과 원문 words oracle의 **전체 ID가 동일함을 먼저 단언**한 뒤 지정된 평문 표를 사용했다(${measure?.wordsBaseline?.equivalentIds??'미확인'}행); 일반적으로 두 의미가 같다는 주장이 아니다. 기존 52조건 파일의 case 수준 respectWords 메타데이터는 과제4 실행 의미와 같이 추가하지 않았으며, 실제 respectWords 옵션은 별도 추가 조건에서 켰다.\n\nC 로캘 한글 LIKE가 포함된 조건은 †이며 평문 대비 성능 판정에서 제외한다. OS 캐시는 비우지 않았고 첫 실행을 콜드 캐시라고 부르지 않는다. 후보 검토 행 수는 DB 내부에서 측정하지 않았으며, 앱 수신 행은 SQL 응답 행 수다. 과제4 A·최종안은 **참고(다른 세션)**로만 제시한다.\n\n`;
if(rows.length){
 md+='## SQL 시간 목표 점검\n\n현재 실측에서 한글 LIKE 조건을 제외한 개별 조건만 평문 SQL 대비 2배 기준으로 점검했다. 전체 제품이나 운영 환경의 통과 판정은 아니다.\n\n| 작업 | 판정 가능 조건 | 2배 이내 | 제외 조건 | SQL 배율 최소 / 중앙 / 최대 |\n|---|---:|---:|---:|---:|\n';
 for(const mode of ['count','list300','listAll']){const all=rows.filter(r=>r.mode===mode),eligible=all.filter(r=>!r.cLocaleKoreanLike),ratios=eligible.map(r=>r.summary.product.sqlMs/r.summary.plain.sqlMs).sort((a,b)=>a-b);if(!ratios.length)continue;const i=ratios.length>>1,median=ratios.length%2?ratios[i]:(ratios[i-1]+ratios[i])/2;md+=`| ${mode} | ${eligible.length} | ${ratios.filter(r=>r<=2).length} | ${all.length-eligible.length} | ${f(ratios[0])} / ${f(median)} / ${f(ratios.at(-1))} |\n`;}
 md+='\n';
}
for(const mode of ['count','list300','listAll']){
 md+=`## ${mode==='count'?'count':mode==='list300'?'목록 300':'목록 전체'}\n\n단위 ms. 전부 현재 측정 중앙값이며 참고 열만 과제4 기록이다.\n\n| # | 조건 전문 | 일치 / 반환 | 평문 SQL / 전체 | R9 SQL / 전체 | SQL / 수신 행 / 복호화 | 참고 A 전체 | 참고 최종안 전체 |\n|---:|---|---:|---:|---:|---:|---:|---:|\n`;
 for(const r of rows.filter(r=>r.mode===mode)){const p=r.summary.plain,v=r.summary.product,[a,b]=ref(r.name,mode);md+=`| ${cases.findIndex(c=>c.name===r.name)+1}${r.cLocaleKoreanLike?'†':''} | ${safe(r.condition)} | ${r.matches} / ${r.returned} | ${f(p.sqlMs)} / ${f(p.totalMs)} | ${f(v.sqlMs)} / ${f(v.totalMs)} | ${v.sqlCalls} / ${v.appRows} / ${v.opens} | ${a} | ${b} |\n`;}
 md+='\n';
}
md+='## 쓰기: 행마다 커밋\n\n새 test_r9_verify_write 표에서 insert 300행, memo 1칸 update 100행, 회사명 update 100행, delete 100행의 순서를 경로마다 실행했다. 첫 시퀀스 별도 + 예열2 + 교차7이며 매 작업 후 전체 원문 값·행 수, 보조행 수, 변경 필드의 정확 검색 count를 대조했다. 초기화·검증은 시간에서 제외하고, 두 경로 모두 행마다 transaction/commit을 끝낸다. 평문 표는 원문+정규화 텍스트와 6개 B-tree/6개 trigram GIN을 가진다. 제품 delete는 Drizzle transaction+delete와 FK cascade다.\n\n| 작업 | 행 수 | 평문 합계 / 행 중앙값 ms | R9 합계 / 행 중앙값 ms | R9 SQL ms / 호출 | R9 복호화 |\n|---|---:|---:|---:|---:|---:|\n';
for(const r of writes?.cases??[]){const p=r.summary.plain,v=r.summary.product;if(!p||!v)continue;md+=`| ${r.op} | ${r.rows} | ${f(p.totalMs)} / ${f(p.medianRowMs)} | ${f(v.totalMs)} / ${f(v.medianRowMs)} | ${f(v.sqlMs)} / ${v.sqlCalls} | ${v.opens} |\n`;}
md+='\n합계는 행별 측정 시간의 합, 행 중앙값은 각 시퀀스의 행 중앙값 7개의 중앙값이다.\n\n## 용량\n\nMiB=2²⁰ bytes. 부모·보조는 각각 100,000행이다. heap 보조는 FSM/VM, TOAST 보조는 TOAST FSM/VM이며 표 색인과 TOAST 색인을 구분한다.\n\n| 표 | heap | heap 보조 | TOAST heap / 보조 / 색인 | 표 색인 | 전체 MiB | bytes/행 |\n|---|---:|---:|---:|---:|---:|---:|\n';
for(const t of capacity?.tables??[])md+=`| ${t.relation} | ${mb(t.heap)} | ${mb(t.heap_fsm+t.heap_vm)} | ${mb(t.toast_heap)} / ${mb(t.toast_aux)} / ${mb(t.toast_indexes)} | ${mb(t.indexes)} | ${mb(t.total)} | ${f(t.bytesPerRow)} |\n`;
if(capacity){const [plain,parent,companion]=capacity.tables;md+=`\n제품 부모+보조 합계 ${mb(parent.total+companion.total)}MiB, 평문 대비 ${f((parent.total+companion.total)/plain.total)}배, 고객 1행당 ${f((parent.total+companion.total)/100000)}bytes.\n`;}
md+='\n칸별 평균 값 크기는 SUM(pg_column_size)/100,000 **추정**이며 페이지·tuple·TOAST 관리·색인 오버헤드를 배분하지 않는다. 물리 표 전체와 더하면 중복 계산이다.\n\n| 칸 | exact | compact | words | single | 후보 토큰 |\n|---|---:|---:|---:|---:|---:|\n';
for(const field of ['name','phone','address','memo','email','company'])md+=`| ${field} | ${['exact','compact','words','single','candidate'].map(s=>f(capacity?.streams.find(r=>r.field===field&&r.stream===s)?.meanValueBytes)).join(' | ')} |\n`;
md+='\n## JOIN\n\n티켓 원문 memo만 검색 가능하게 새 모델에 넣고 ID/customerId/scope를 유지했다. 조건은 tickets.memo contains "서비스" AND customers.company = "서울서비스 담당", ticket ID 오름차순이다. 고객 6칸+티켓 memo를 양쪽 경로에서 같은 값으로 반환한다. 평문은 지정 고객 평문 표와 원본 티켓 표를 JOIN한다.\n\n';
md+=`티켓 적재 ${ticket?.loaded??0}/100,000, ${f(ticket?.elapsedMs)}ms. ${ticket?.limitReached?'20분 안에 적재가 끝나지 않아 JOIN은 미측정.':''}\n\n| limit | 반환 | 평문 SQL / 전체 ms | R9 SQL / 전체 ms | SQL / 수신 행 / 복호화 |\n|---:|---:|---:|---:|---:|\n`;
for(const r of join?.rows??[]){const p=r.summary.plain,v=r.summary.product;md+=`| ${r.limit} | ${r.returned} | ${f(p.sqlMs)} / ${f(p.totalMs)} | ${f(v.sqlMs)} / ${f(v.totalMs)} | ${v.sqlCalls} / ${v.appRows} / ${v.opens} |\n`;}
md+='\nJOIN도 첫 실행 별도+예열2+교차7이며 매회 원문 oracle의 ID 순서·투영 값을 단언했다. 같은 고객이 반복되면 요청 내 인증 캐시가 재사용되므로 복호화는 고유 고객 수×6+티켓 수다. 한글 LIKE가 들어간 이 조건의 평문 대비 배율도 성능 목표 판정에서 제외한다.\n\n## 구간별 원자료와 한계\n\n전처리/SQL/SQL 사이/후처리/전체, SQL 호출·앱 수신 행·인증 복호화 필드 수는 metrics.csv와 measure.json에 전 조건·경로별로 보존했다. 지표별 중앙값은 서로 합산되지 않을 수 있다. writes.json에는 7회×각 행의 세부 지표, capacity.json에는 카탈로그·함수·색인과 용량 원자료, join.json에는 JOIN 반복을 보존했다. 원문을 보고 추측한 보안 판단은 수행하지 않았으며 이 작업은 보안 검증을 대체하지 않는다.\n\n';
const errors=[...(load?.errors??[]),...(measure?.errors??[]),...(writes?.errors??[]),...(ticket?.errors??[]),...(join?.errors??[])];
md+=`기록된 오류 ${errors.length}개${errors.length?': '+errors.map(e=>safe(e.message)).join('; '):''}. 미완료 항목은 첫 상태 문장에 표시한다. 로컬 합성 fixture 결과이며 운영 보장·보안 인증이 아니다.\n\n재현 스크립트: bench/verify-r9/{load,measure,writes,capacity,load-tickets,join}.ts 및 report.mjs. 새 스키마를 생성하는 load/writes/load-tickets는 기존 스키마가 있으면 중단하며 보호 표를 지우거나 재설정하지 않는다. 조회는 코디네이터의 수정 완료 통지 후 최신 빌드+extraMigrationSql 설치가 선행되어야 한다. 모든 DB 실행은 assertDisposable·포트 확인과 measure.lock 소유하에 수행한다.\n`;
md=md.replace('기존 52조건 파일의 case 수준 respectWords 메타데이터는 과제4 실행 의미와 같이 추가하지 않았으며, 실제 respectWords 옵션은 별도 추가 조건에서 켰다.', '기존 52조건 파일의 case 수준 respectWords 메타데이터도 제품 API 옵션으로 반영했다. 과제4 참조 실행은 해당 옵션을 반영하지 않았으므로 그 두 조건의 역사 수치는 특히 직접 비교하지 않는다. 추가 respectWords 조건까지 세 조건 모두 원문 words oracle과 평문 기준의 전체 ID 동등성을 단언했다.');
const keys=['preMs','sqlMs','betweenMs','postMs','totalMs','sqlCalls','appRows','opens'];
md=md.replace('현재 실측에서 한글 LIKE 조건을 제외한', '출처: measure.json. 현재 실측에서 한글 LIKE 조건을 제외한');
md=md.replaceAll('단위 ms. 전부 현재 측정 중앙값이며 참고 열만 과제4 기록이다.', '출처: measure.json·cases.json; 참고 열은 .local/research/task4-full-table.md. 단위 ms. 현재 측정 중앙값이며 참고 열만 과제4 기록이다.');
md=md.replace('새 test_r9_verify_write 표에서', '출처: writes.json. 새 test_r9_verify_write 표에서');
md=md.replace('MiB=2²⁰ bytes.', '출처: capacity.json. MiB=2²⁰ bytes.');
md=md.replace('칸별 평균 값 크기는', '출처: capacity.json의 streams. 칸별 평균 값 크기는');
md=md.replace('티켓 원문 memo만 검색 가능하게', '출처: ticket-load.json·join.json. 티켓 원문 memo만 검색 가능하게');
md+='\n재현·검수: install.ts --fix-announced → measure.ts → writes.ts → capacity.ts → load-tickets.ts → join.ts → report.mjs → verify-results.mjs. install.ts의 최신 빌드와 extraMigrationSql 재설치는 데이터와 기존 형식을 유지한다. capacity.ts는 설치 함수 본문 4개와 MAIN 카탈로그 설정을 최종 공개 API 출력에 대조했다. 최초 적재의 extraMigrationSql에도 MAIN 설정이 포함되어 있었다.\n';
if(finish)md+='\n최종 검수: 조회 2,300회(첫 실행·예열 포함)와 쓰기·JOIN의 실행 중 oracle 단언을 통과했다. verification.json은 반복 횟수·계측 값·물리 용량 합계·보고서 동일성·락 해제를 재검수한다. 최종 빌드, 측정 스크립트 TypeScript 검사, docs:check도 통과했다. 데이터 유지 지시에 따라 측정 스키마를 보존했으며 보호 표는 읽기만 했다.\n';
const csv=[['name','mode','path','matches','returned',...keys].join(',')];for(const r of rows)for(const path of ['plain','product'])csv.push([r.name,r.mode,path,r.matches,r.returned,...keys.map(k=>r.summary[path][k])].join(','));
if(revision){
 md=md.replace('# R9 제품 API 독립 검수',`# R9 제품 API 독립 검수 — ${revision.commit.slice(0,7)}\n\n조회 115개와 JOIN 20/300은 ${revision.commit.slice(0,7)}에서 재측정했다. **쓰기·용량은 04994b2 실측을 재사용**하고, 고객 초기 적재와 티켓 적재도 그대로 유지했다. 제품 src 전체 diff는 native-search.ts와 candidate-sql.ts의 목록 정렬·후보 조회 변경뿐이며 쓰기 경로·암호화·저장 형식·마이그레이션 구현은 불변이다(revision.json). 아래 주 표는 새 조회 결과이고, 이전 판 전체 보고서는 문서 마지막에 별도로 보존했다.`);
 md=md.replace('## 쓰기: 행마다 커밋','## 쓰기: 행마다 커밋 — 04994b2 실측 유지').replace('## 용량\n','## 용량 — 04994b2 실측 유지\n');
 md=md.replace('최초 적재의 extraMigrationSql에도 MAIN 설정이 포함되어 있었다.', '최초 적재의 extraMigrationSql에도 MAIN 설정이 포함되어 있었다. 이번 재측정에서는 main·JOIN의 함수만 재설치하고 main을 ANALYZE했으며 쓰기·용량·적재는 재실행하지 않았다.');
 const priorMeasure=JSON.parse(readFileSync(`${OUT}/prior-04994b2/measure.json`,'utf8'));
 md+='\n## 목록 정렬 변경 전후의 대표 조건\n\n출처: prior-04994b2/measure.json 및 measure.json, list300의 제품 경로 중앙값(ms). 동일 데이터·조건·정렬·투영으로 다른 시점에 측정했으므로 시간 변동을 포함한다. 전체 56조건은 위 최신 표와 아래 이전 판에 모두 보존했다.\n\n| 조건 | 반환 | 04994b2 SQL / 전체 | a4231b4 SQL / 전체 |\n|---|---:|---:|---:|\n';
 for(const name of ['coarse_company_zero','sub_mid','sub_rare','word_boundary','affix_endsWith_email','like_prefix']){
  const previous=priorMeasure.rows.find(r=>r.name===name&&r.mode==='list300'),current=rows.find(r=>r.name===name&&r.mode==='list300');
  if(previous&&current)md+=`| ${name} | ${current.returned} | ${f(previous.summary.product.sqlMs)} / ${f(previous.summary.product.totalMs)} | ${f(current.summary.product.sqlMs)} / ${f(current.summary.product.totalMs)} |\n`;
 }
 md+='\n## 이전 판 보존 — 04994b2\n\n아래는 최초 제출 보고서의 내용이다. 이전 원자료와 CSV·검수 기록은 [prior-04994b2/report-ko.md](prior-04994b2/report-ko.md)와 같은 디렉터리에 보존했다. 시점이 다른 측정이며 최신 성능 판정에는 위 a4231b4 조회 표를 사용한다.\n\n'+readFileSync(`${OUT}/prior-04994b2/report-ko.md`,'utf8').replace(/^#/gm,'###');
}
mkdirSync(OUT,{recursive:true});writeFileSync(`${OUT}/metrics.csv`,csv.join('\n')+'\n');writeFileSync(`${OUT}/report-ko.md`,md);writeFileSync('.local/research/final-measure-v-astra.md',md);
console.log(JSON.stringify({complete:finish,queryRows:rows.length,writes:writes?.complete,join:join?.complete,reportBytes:Buffer.byteLength(md)}));
