import {hash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {hex} from '../../../src/core/bytes.js';
import {searchPieces} from '../../../src/core/search-tokens.js';
import {ActiveCodec,norm,scope} from '../../final-review/r9-impl/codec.js';
import {makeProbes,learn,type Strategy} from '../../final-review/r9-impl/probes.js';
import {attacker} from '../../final-review/r9-impl/attack.js';
import {loadRows,shuffled} from '../../attack-extra/common.js';
import {assert,save} from './common.js';
const raw=await loadRows(),values=raw.map(r=>norm(r.phone)),ref=raw.slice(0,10000).map(r=>r.phone),victim=raw.slice(10000,11000),prior=JSON.parse(readFileSync('bench/results/2026-09-29-final-review/r9-impl/bits.json','utf8'));
const result:any={started:new Date().toISOString(),complete:false,rows:raw.length,field:'phone',otherFields:'Unchanged 16 bits',fixtureDigest:hash('sha256',raw.map(r=>r.id).join('\n')),attack:[],selection:[],search:[],summary:[],validation:{priorAttackMatches:0,noFalseNegatives:0,actual16Rows:0},protocol:'Same fixture, key, scope, normalization and attacker as preceding bits study; actual stored hyphens retained'};
const stats=(xs:number[])=>{const a=[...xs].sort((x,y)=>x-y);return {mean:a.length?a.reduce((s,x)=>s+x,0)/a.length:0,p95:a.length?a[Math.ceil(a.length*.95)-1]:0,max:a.at(-1)??0};};
const freq=[new Map<string,number>(),new Map<string,number>(),new Map<string,number>()];for(const value of values){const c=Array.from(value);for(let w=2;w<=4;w++){const terms=new Set<string>();for(let j=0;j+w<=c.length;j++)terms.add(c.slice(j,j+w).join(''));for(const t of terms)freq[w-2].set(t,(freq[w-2].get(t)??0)+1);}}
const queries:{term:string;width:number;matches:number;group:string}[]=[];
for(let w=2;w<=4;w++){const all=[...freq[w-2]],rare=all.filter(([,n])=>n<=10),chosen=shuffled(rare,20260929+w).slice(0,200);result.selection.push({width:w,distinct:all.length,minFrequency:Math.min(...all.map(([,n])=>n)),rareAvailable:rare.length,rareSampled:chosen.length});for(const [term,matches]of chosen)queries.push({term,width:w,matches,group:'rare-1-10'});if(!chosen.length)for(const [term,matches]of all.sort((a,b)=>a[1]-b[1]||a[0].localeCompare(b[0])).slice(0,200))queries.push({term,width:w,matches,group:'lowest-frequency-control'});}
for(const bits of [16,12]){
 const codec=new ActiveCodec('phone','product',scope,bits);
 for(const strategy of ['whole-values','packed-pieces'] as Strategy[]){const probes=makeProbes(ref,'phone',strategy),pieces=probes.map(v=>codec.pieces(v)),views=probes.map(v=>({tokens:codec.tokens(v),plainBytes:Buffer.byteLength(v),length:Array.from(norm(v)).length}));for(const n of [10,100,1000]){const mapping=learn(pieces.slice(0,n),views.slice(0,n).map(v=>v.tokens)),predict=attacker({field:'phone',pieces:v=>codec.pieces(v)},ref,probes.slice(0,n),views.slice(0,n),mapping);let correct=0;for(const row of victim){const g=predict({tokens:codec.tokens(row.phone),plainBytes:Buffer.byteLength(row.phone),length:Array.from(norm(row.phone)).length});correct+=Number(g.value===norm(row.phone));}assert.equal(correct,prior.attack.find((r:any)=>r.bits===bits&&r.field==='phone'&&r.strategy===strategy&&r.n===n).values);result.validation.priorAttackMatches++;result.attack.push({bits,strategy,n,correct,total:victim.length,pct:correct/victim.length*100});}}
 const queryTokens=queries.map(q=>[...new Set(searchPieces(codec.p,q.term,'contains').map(p=>codec.token(hex(p))))]),wanted=new Set(queryTokens.flat()),postings=new Map<string,number[]>([...wanted].map(t=>[t,[]]));
 for(let i=0;i<raw.length;i++){for(const t of codec.tokens(raw[i].phone))postings.get(t)?.push(i);if(i<5&&bits===16){await codec.validate(raw[i].phone);result.validation.actual16Rows++;}if(i%1000===999)codec.clearValueCache();}
 const search=queries.map((q,qi)=>{const lists=queryTokens[qi].map(t=>postings.get(t)!).sort((a,b)=>a.length-b.length),sets=lists.slice(1).map(xs=>new Set(xs)),ids=lists[0].filter(i=>sets.every(s=>s.has(i))),candidateSet=new Set(ids);let matches=0;for(let i=0;i<values.length;i++)if(values[i].includes(q.term)){matches++;assert(candidateSet.has(i));}assert.equal(matches,q.matches);result.validation.noFalseNegatives+=matches;return {...q,bits,candidates:ids.length,factor:ids.length/matches};});
 result.search.push(...search);result.summary.push(...[2,3,4].map(width=>{const qs=search.filter(q=>q.width===width),base=result.search.filter((q:any)=>q.bits===16&&q.width===width);return {bits,width,group:qs[0]?.group??'none',n:qs.length,candidates:stats(qs.map(q=>q.candidates)),factor:stats(qs.map(q=>q.factor)),relative16:stats(qs.map((q,i)=>q.candidates/base[i].candidates)),ratioOfMeans:qs.length?qs.reduce((s,q)=>s+q.candidates,0)/base.reduce((s:number,q:any)=>s+q.candidates,0):null};}));save('token-bits','phone',result);console.log(JSON.stringify({bits,selection:result.selection,summary:result.summary.filter((s:any)=>s.bits===bits)}));
}
result.complete=true;result.finished=new Date().toISOString();save('token-bits','phone',result);console.log('COMPLETE phone bits');
