import {readFileSync,readdirSync} from 'node:fs';
import {hash} from 'node:crypto';
import {assert,OUT,save} from './common.js';
const read=(name:string)=>JSON.parse(readFileSync(`${OUT}/${name}.json`,'utf8'));
let assertions=0;
function check(condition:unknown,message:string){assert.ok(condition,message);assertions++;}
const dataset=read('dataset');check(dataset.disjointIds&&dataset.victimRows===10000&&dataset.referenceRows===10000,'Disjoint reference/victim cohorts');
const metric=(m:any)=>{for(const [a,b]of [['values','rows'],['characters','characterTotal'],['positions','positionTotal'],['mostly','rows']])check(m[a]>=0&&m[a]<=m[b],`${a} denominator`);};
const observations=readdirSync(OUT).filter(f=>f.startsWith('observation-')&&f.endsWith('.json'));check(observations.length===7,'Six fixture fields plus public reviews');
let productChecks=0,historicalChecks=0,researchComparisons=0;
for(const name of observations){const d=JSON.parse(readFileSync(`${OUT}/${name}`,'utf8'));check(d.results.map((r:any)=>r.observations).join(',')==='10,100,1000','All observation checkpoints');check(d.historicalSourceHash?.length===64,'Pre-R9 source pinned');check(d.candidateOnly.includes('ciphertext byte length'),'Historical ciphertext-length baseline enabled');productChecks+=d.productWebCryptoChecks;historicalChecks+=d.historicalWebCryptoChecks;researchComparisons+=d.researchComparisons;
 let previous={characters:0,positions:0,distinctKeys:0};for(const r of d.results){metric(r);metric(r.candidateOnlyKnownQuery);metric(r.candidateAndPositionsKnownQuery);metric(r.keyOnlyFrequency);check(r.characters>=previous.characters&&r.positions>=previous.positions&&r.distinctKeys>=previous.distinctKeys,'Known observation recovery monotone');check(r.candidateAndPositionsKnownQuery.characters>=r.characters,'Combined inference preserves decoded characters');check(r.randomPositionExpectedCorrect<=r.positions,'Random offset baseline bounded');previous=r;}
}
for(const name of readdirSync(OUT).filter(f=>f.startsWith('statistics-')&&f.endsWith('.json'))){const d=JSON.parse(readFileSync(`${OUT}/${name}`,'utf8'));check(d.positionLengthRedundant,'Position length redundancy mechanically checked');for(const r of d.rows){metric(r);check(r.correctlyMappedTokens<=r.uniquelyMappedTokens,'Signature mapping precision');check(r.rows===10000-r.knownRows,'Known rows excluded from scoring');}for(const known of [0,1,10,100]){const a=d.rows.find((r:any)=>r.knownRows===known&&r.mode==='frequency+length'),b=d.rows.find((r:any)=>r.knownRows===known&&r.mode==='frequency+length+positions');for(const key of ['values','characters','positions'])check(a[key]===b[key],'Redundant position-length feature changes no prediction');}}
const backup=read('backup');check(backup.complete&&backup.schemaDeleted,'Owned snapshot schema removed');check(backup.codecDatabaseChecks===768&&backup.roundtripFields===768,'Actual stored-byte and managed-write roundtrip checks');for(const c of backup.cases){check(c.saltsChanged===64&&c.exactSaltsChanged===64&&c.exactStampsChanged===64&&c.ciphertextsChanged===64&&c.stampIntersection===0,'Fresh salt and ciphertext after each write');check(c.unchangedFieldCells===c.checkedUnchangedFieldCells,'Unchanged fields unchanged');check(c.correctChangedPieces<=c.guessedPieces&&c.correctChangedPieces<=c.changedPieces,'Changed-piece inference bounds');}
const timing=read('timing');check(timing.canonicalQueryGroups<timing.queryRows,'Equivalent query groups held together');for(const r of timing.results){check(r.samples===385,'Seven real repeats for 55 queries');check(r.binAccuracyPercent>=0&&r.binAccuracyPercent<=100,'Timing inference bounds');}
const sources=[...readdirSync('bench/attack-extra').filter(f=>f.endsWith('.ts')).map(f=>'bench/attack-extra/'+f),'src/core/search-tokens.ts','src/core/search-stamps.ts','src/core/stamp-query.ts','src/adapters/drizzle/v0.45/native.ts'];
save('verification',{assertions,productWebCryptoChecks:productChecks,historicalWebCryptoChecks:historicalChecks,researchComparisons,storedFieldChecks:768,roundtripFields:768,schemaDeleted:true,complete:true,sha256:Object.fromEntries(sources.map(p=>[p,hash('sha256',readFileSync(p))]))});
console.log(`PASS ${assertions} evidence assertions; product ${productChecks}, pre-R9 ${historicalChecks}, research ${researchComparisons}, stored fields 768, roundtrip fields 768; schema deleted`);
