import {readFileSync,readdirSync,writeFileSync} from 'node:fs';
const root='bench/results/2026-09-30-mongo-reeval/m1-astra',audit=JSON.parse(readFileSync(`${root}/audit.json`,'utf8'));
const old=JSON.parse(readFileSync('bench/results/2026-09-30-competitor-sim/m1-astra/verification.json','utf8'));
const strong=JSON.parse(readFileSync(`${root}/strong-dictionary.json`,'utf8'));
const ledger=JSON.parse(readFileSync(`${root}/ledger-frequency.json`,'utf8'));
const fields=['name','phone','address','memo','email','company'],names:Record<string,string>={name:'이름',phone:'전화',address:'주소',memo:'메모',email:'이메일',company:'회사'};
const files=readdirSync(root).filter(f=>f.startsWith('ab-')&&f.endsWith('.json')).map(f=>JSON.parse(readFileSync(`${root}/${f}`,'utf8')));
// Closure reads only already completed files; it never starts an attack.
const deltaFiles=readdirSync(root).filter(f=>f.startsWith('delta-')&&f.endsWith('.json')).map(f=>JSON.parse(readFileSync(`${root}/${f}`,'utf8')));
audit.best=files.flatMap(x=>[0,100,500].flatMap(known=>['index','native_shape'].map(channel=>({model:x.model,field:x.field,...x.results.filter((r:any)=>r.known===known&&r.channel===channel).sort((a:any,b:any)=>b.correct-a.correct)[0]}))));
audit.deltas=deltaFiles.flatMap(x=>x.cases.map((r:any)=>({model:x.model,field:x.field,...r})));
const pct=(v:number|undefined)=>v===undefined?'미완료':v.toFixed(3),choose=(model:string,field:string,known:number,channel:string)=>audit.best.find((r:any)=>r.model===model&&r.field===field&&r.known===known&&r.channel===channel);
let out=`# MongoDB식 발생별 태그 재평가 — A/B 및 두 스냅샷\n\n## 미검증·한계 먼저\n\n${audit.complete?'두 모형 × 6칸의 A/B 및 삽입·수정 전후 배치 실험을 완료했다.':'진행 중인 중간 보고다. 미완료는 0으로 세지 않는다.'} 제품 코드와 DB는 변경하거나 실행하지 않았다. 실제 MongoDB SDK·서버 침해 실험이 아니라 공식 규칙을 반영한 메모리 누출 모형이다. 실제 BSON 태그 배열 순서, compaction 트랜잭션별 로그, ECOC 개별 문서와 운영 cleanup 이력은 재현하지 않았다. 따라서 아래 수치는 실제 MongoDB의 복원율 상한이나 보안 인증이 아니다.\n\n이름·메모·이메일은 피해 값이 참조 사전에 없으므로 사전 선택 공격의 0%가 특히 제한적이다. 이 세 칸의 사전 밖 일반문장 조립 공격은 미구현이다. 전화는 공개 형식 DFS와 참조사전의 같은 관측 모양에 서로 다른 두 값이 있는지 확인했지만, 전체 장부와 동시에 맞는 모든 피해 전화 집합의 유일성은 증명하지 않았다. 정규화 값 전체를 맞힌 비율이며 원문 공백 복원율이 아니다.\n\n## 결론\n\n1. 발생마다 다른 태그에서는 알려진 원문의 태그가 다른 피해 행으로 전이되지 않았다. 기존 S0 전화 99.79/99.80% 공격이 이용한 재사용 토큰 관계가 사라진다는 차이는 관찰되었지만, 이것만으로 모든 공격에 안전하다고 결론내리지 않는다.\n2. 공개 길이·태그 수는 별도 채널로 남는다. 작은 회사명 사전은 발생별 태그만으로 보호되지 않으며, C-port와 C-mongo의 패딩 차이를 별도로 읽어야 한다.\n3. 전후 두 배치 스냅샷과 매 쓰기/compaction 트랜잭션 로그는 다른 공격자다. 평문 장부의 변화량으로 익명 조각 라벨을 일부 추정해도, 키 없이 그 장부를 기존 행 태그에 연결할 수 있다고 가정하지 않았다.\n\n## 실험 계약\n\n기존 fixture를 같은 seed714029로 재생한 피해10,000행/독립 참조10,000행, 여섯 칸, 같은 고정 키 모형을 사용했다. 같은 정규화 입력은 앱 공통 전처리이며 타사 기본 동작이라는 주장이 아니다. A는 알려진 피해 원문0행, B1/B5는 원래 피해 순서의 앞100/500행을 알고 남은 행만 채점한다. 모형에서 지원하지 않는 값은 분모에서 제외하고 별도 기록했다. C-mongo partial 최대60글자 초과 메모를 잘라내거나 최대 길이를 늘리지 않았다.\n\n| 모형 | 검색 조각/태그 | 장부 관측 | 길이 관측 |\n| --- | --- | --- | --- |\n| C-port | 전체값 + 중복 제거 2..10글자; 주소·이메일은 앞·뒤 조각도; 64bit 발생 태그 | 조각별 익명 ID와 평문 누적 n | 정규화 UTF8 바이트+28 및 정확 태그 수 |\n| C-mongo | partial 2..10글자, 내부 exact1 + 공식 수식 패딩; 256bit 발생 태그; contention8(9버킷) | 암호화 카운터와 독립 PRF ID; 압축 후 그룹별 암호화 anchor로 이상화 | UTF8 블록 기반 E와 패딩 태그 수; 고정 envelope 생략 |\n\nC-mongo 내부 exact 태그는 공개 equality 검색 지원을 뜻하지 않는다. 두 모형의 지원 검색·패딩이 다르므로 제품 전체 기능이 동등하다는 주장을 하지 않는다. C-port의 combined 구성은 과거 PostgreSQL 이식의 연구 설정이다.\n\n## A/B 전체 값 복원율\n\n단위 %. 이름 붙인 완결 공격 중 집계 맞힘이 가장 큰 공격을 선택했다(행별 정답 투표 아님, 사후 최댓값). 기존 S0/Bloom은 동일 데이터의 보존된 색인 전수 결과를 인용했다. 새 index에는 공개 태그 개수가 포함되며 native에는 해당 모형 암호문 길이도 포함된다.\n\n| 알려진 행 | 칸 | S0 색인 | Bloom 색인 전수 | C-port 색인 | C-port 길이 | C-mongo 색인 | C-mongo 길이 |\n| --- | --- | --- | --- | --- | --- | --- | --- |\n`;
for(const k of [0,100,500])for(const f of fields){const oldPct=(model:string)=>old.best.find((r:any)=>r.model===model&&r.field===f&&r.known===k&&r.channel==='index')?.pct;out+=`| ${k} | ${names[f]} | ${pct(oldPct('S0'))} | ${pct(oldPct('CipherStash-match'))} | ${pct(choose('C-port',f,k,'index')?.pct)} | ${pct(choose('C-port',f,k,'native_shape')?.pct)} | ${pct(choose('C-mongo',f,k,'index')?.pct)} | ${pct(choose('C-mongo',f,k,'native_shape')?.pct)} |\n`;}
out+=`\n회사명 A의 무정보 최빈값 추측은28.63%, 참조분포 무작위는15.07%, 고유값 균등 무작위는5.99%다. C-mongo 공개 모양30.54%는 최빈값보다1.91%p 높고, C-port70.17%는41.54%p 높다. 단순 맞힘률 전부를 암호 해독 성과로 부르지 않는다. 원시 JSON에 모든 조건의 무작위 기준선도 보존했다.\n\nBloom 전화의 강한 충돌 공격은 별도500행 표본에서 B1 0/500(Wilson95% 0–0.762%), B5 52/500=10.4%(8.019–13.384%)였다. 이를 전수0%와 혼동하지 않는다. S0 전화는 2백만상태 전수, Bloom 강화는20,000상태 표본이므로 계산 예산도 다르다. 기존 세부 결과는 [이전 보고서](../../2026-09-30-competitor-sim/m1-astra/report-ko.md)에 있다.\n\n### 분모·관측 규모\n\n모두 피해 입력10,000행 기준이다. 태그/장부는 논리 원소 개수이며 저장 바이트·DB 성능 측정이 아니다.\n\n| 모형 | 칸 | 지원 피해 행 | A/B1/B5 분모 | 태그 총수 | 압축 전/후 장부 행 | 평문 카운터 행 |\n| --- | --- | --- | --- | --- | --- | --- |\n`;
for(const x of files){const den=[0,100,500].map(k=>x.results.find((r:any)=>r.known===k).rows);out+=`| ${x.model} | ${names[x.field]} | ${10000-x.unsupported.length} | ${den.join('/')} | ${x.uniqueness.tagOccurrences} | ${x.esc.beforeRows}/${x.esc.afterCompactionRows} | ${x.esc.plaintextCounters} |\n`;}
out+=`\n### 같은 강한 공격을 옮긴 방법\n\n기존 group/piece/rank 빈도, 알려진 조각 교집합, 전체 색인 지문 공격을 같은 함수로 실행했다. 공개 형태(태그 개수, 네이티브 암호문 길이)에 조건부 사전 빈도 추측을 추가했다. 원래 공통 dictionaryPredictor도 발생별 태그에 맞는 등가 축약으로 실행했다: 알려진 각 태그의 incidence는 한 행뿐이며, 피해 태그와 교집합이 없으면 피해의 알려진 조각 signature는 빈 집합이다. 원래 함수와 작은 알려진 부분집합을 직접 대조했다(${strong.reductionChecks}회). 이 축약은 비밀 키·정답·장부-행 연결을 사용하지 않는다. 전체 결과는 strong-dictionary.json에 있다.\n\nS0의 전화 조립기는 start/adjacent/skip/end의 재사용 라벨을 전제로 하므로 다른 조각 스키마에 그대로 호출해 나온 실패를 보안 결과로 쓰지 않았다. 발생별 모형은 공개 참조 전화의 자리별 숫자·하이픈 형식을 사용하고, 공개 모양과 양립하는 서로 다른 전화들을 찾았다.\n\n| 모형 | 공개 참조의 서로 다른 두 값이 같은 모양인 피해 행 | 원래 DFS 상한 도달 행 | 범위 |\n| --- | --- | --- | --- |\n`;
for(const x of audit.phoneCertificates)out+=`| ${x.model} | ${x.rowsWithAtLeastTwoReferenceWitnesses}/10000 | ${x.dfsCappedRows}/10000 | 모양만의 모호성; 전체 장부 결합 증명 아님 |\n`;
out+=`\n참조사전 인증은 DFS 상한을 숨기거나 복원 성공으로 바꾼 것이 아니다. 20,000상태에서 못 끝난 행은 그대로 남겼다. 실제 알려진 원문과 피해 행 사이 태그 교집합은 모든 완료 A/B 조건에서0이었다. 일반 A/B 빈도 함수는 검색 가능한 조각을 사용하고, 별도 강한 사전 축약에는 C-mongo 내부 exact와 반복 fake의 incidence까지 포함했다.\n\n### 장부만의 A 빈도 공격\n\nC-port 실제 snapshot ESC digest와 일치하는 익명 ID/n 목록에 참조 조각 빈도를 순위 대응시켰다. 이는 **익명 조각 라벨 맞힘**이며 행 원문 복원이 아니다. 정답 ID 연결은 평가에만 썼다. C-mongo에는 평문 n이 없으므로 이 입력을 임의로 제공하지 않았다.\n\n| 칸 | 상위100 카운터의 라벨 맞힘 | 참조빈도가 하나뿐인 exact-count 추측 맞힘/시도 |\n| --- | --- | --- |\n`;
for(const r of ledger.results)out+=`| ${names[r.field]} | ${r.rankTop100.correct}/${r.rankTop100.attempted} | ${r.uniqueExactCount.attempted?r.uniqueExactCount.correct+'/'+r.uniqueExactCount.attempted:'추측 없음'} |\n`;
out+=`\n## 삽입·수정 전후 두 스냅샷\n\n독립 참조에서 seed108029로 고른100/1000행을 넣는다. 삽입 후 상태를 기준으로 기존 피해의 앞100/1000행을 해당 참조 값으로 전체 수정한다. 공격자는 새 값과 두 배치의 끝 스냅샷만 받는다. 배치 내부 개별 쓰기 시각/트랜잭션 그룹은 주지 않는다. 수정된 행의 새 값은 이미 알고 있으므로 복원 성공 분모에서 제외한다. 원래 값 추측은 수정 전 공개 모양으로 따로 기록했다. 작은 문자 편집에 따른 전후 값 상관 공격은 측정 안 함이다.\n\n아래는1000건 배치의 대표 결과이며100건 및 기존 값 지표는 delta JSON에 있다. 변화량 기반 전체 지문·공개 모양 공격과 참조 모양만의 기준선을 비교한다.\n\n| 모형/칸 | 작업/압축 | 맞힘/분모 (%) | 참조 모양만 % | 알려진 새 태그가 기존 행과 겹침 | 장부 추가/제거/변경 | 유일 조각 라벨 후보/실제 맞힘 |\n| --- | --- | --- | --- | --- | --- | --- |\n`;
for(const r of audit.deltas.filter((r:any)=>r.N===1000)){const q=r.unmodifiedVictims;out+=`| ${r.model}/${names[r.field]} | ${r.operation}/${r.phase==='precompaction'?'전':'양끝 압축'} | ${q.correct}/${q.rows} (${pct(q.pct)}) | ${pct(r.referenceOnly.pct)} | ${r.knownTargetTagOverlapRows} | ${r.esc.added}/${r.esc.removed}/${r.esc.changed} | ${r.esc.uniqueBatchCounterLabels}/${r.esc.evaluationOnlyCorrectCounterLabels??'해당 없음'} |\n`;}
out+=`\n장부 라벨 맞힘 계산에서만 평가자가 원래 카운터 ID와 비교했다. 이 정답은 후보 선택이나 행 복원에 쓰지 않았다. C-mongo의 같은 anchor ID에서 암호문만 바뀐 경우도 '변경'에 포함했다. 수정하지 않은 피해 행의 태그 변화와 수정 행의 이전 태그 잔존은 완료된 모든 조건에서0이었다. 전후 장부는 삽입량·활동량을 누출하며 C-port는 값별 정확 누적량까지 보이지만, 그 사실만으로 행별 원문 라벨이 생기지는 않는다.\n\n## 근거·해석 경계\n\n공식 규칙과 소스 대조는 [v-astra 규칙표](../v-astra/model-rules-ko.md)에 있다. [공식 compaction 문서](https://www.mongodb.com/docs/manual/core/queryable-encryption/fundamentals/manage-collections/)와 [USENIX Security 2023 분석](https://www.usenix.org/system/files/usenixsecurity23-gui_1.pdf)을 구분했다. 해당 논문의 강한 로그 공격은 삽입 트랜잭션의 문서 연결과 compaction 작업별 상태 연결을 이용한다. 본 실험처럼 연결 정보를 제거한 두 끝점만을 그 공격자와 동일시할 수 없다. 본 모형의 낮은 복원율로 그 공격을 반박하지 않는다.\n\nMongoDB [서버 태그 생성 코드](https://github.com/mongodb/mongo/blob/r8.2.0/src/mongo/crypto/fle_crypto.cpp)와 [클라이언트 문자열 인코딩](https://github.com/mongodb/libmongocrypt/blob/master/src/mc-str-encode-string-sets.c)은 배열 순서가 남는 경로를 가진다. 공통 모형은 이를 정렬된 집합으로 추상화했다. 특히 질의 관찰에서 배열 내 위치와 공개 조각 순서를 결합하는 공격은 후속 실제SDK 검증이 필요하다. C/D 질의 관찰 결과는 r9-impl 담당이며 여기의 A/B0%와 합쳐 무조건 안전으로 요약하지 않는다.\n\n## 재현·검증\n\n- \`rtk proxy node --import tsx bench/mongo-reeval/m1-astra/run-batch.ts C-port\` 또는 마지막 인자를 C-mongo로 실행한다. 완료 JSON은 건너뛴다. run-ab는 생성한 encoder를 이어서 runDelta에 재사용한다.\n- \`rtk proxy node --import tsx bench/mongo-reeval/m1-astra/verify-strong.ts\`, 이어서 audit.ts, report.ts를 실행한다.\n- 현재 ${audit.files}/24 원시 파일, ${audit.aggregates} 집계, ${audit.witnesses} 저장 witness 재채점이 통과했다. 독립 공개 공격 재실행은 v-astra의 검산 산출물을 별도로 확인한다. audit.json에 공통 모델·공격·자기 스크립트 SHA256을 보존했다.\n\n결과는 이 fixture·이 모형·이 공격의 실측이며, 운영 DB 성능·보안 인증·모든 공격의 상한으로 사용하지 않는다.\n`;
const coverage='## 중단 시점 보존 범위\n\n| 칸 | C-port A/B | C-mongo A/B | C-port 전후 | C-mongo 전후 |\n| --- | --- | --- | --- | --- |\n'+fields.map(f=>'| '+names[f]+' | '+['C-port','C-mongo'].map(model=>files.some(x=>x.model===model&&x.field===f)?'완료':'미측정').join(' | ')+' | '+['C-port','C-mongo'].map(model=>deltaFiles.some(x=>x.model===model&&x.field===f)?'완료':'미측정').join(' | ')+' |').join('\n')+'\n\n콘솔에 일부 중간 값이 나온 실행도 완료 JSON이 없으면 미측정으로 분류했다. 실행 중이던 다섯 세션은 중단했고 소유 run-ab/run-batch/run-delta 프로세스가 남지 않았음을 확인했다.\n\n';
out=out.replace('# MongoDB식 발생별 태그 재평가 — A/B 및 두 스냅샷\n\n','# MongoDB식 발생별 태그 재평가 — A/B 및 두 스냅샷\n\n**사용자 결정으로 중단, 부분 결과.**\n\n');
out=out.replace('진행 중인 중간 보고다. 미완료는 0으로 세지 않는다.','추가 실행 없이 저장된 완결 결과만 보존했다. 미측정은 0으로 세지 않는다.');
out=out.replace('## A/B 전체 값 복원율',coverage+'## A/B 전체 값 복원율');
out=out.replace('현재 '+audit.files+'/24 원시 파일,','중단 전 검산 범위는 '+audit.files+'/24 원시 파일,');
out=out.replace('결과는 이 fixture','최종 보존은 '+(files.length+deltaFiles.length)+'/24 원시 파일이다. 중단 전 audit 및 독립 검산의 범위를 최종 보존 전체에 확대하지 않는다. strong-dictionary.json도 완료된 '+strong.results.length+'/36조건까지만 보존했다. 추가 실험·공격 재실행은 중단 후 하지 않았다.\n\n결과는 이 fixture');
out=out.replaceAll('미완료','미측정');
out=out.replace('native에는 해당 모형 암호문 길이도 포함된다.','길이 열은 태그 수와 해당 모형 암호문 길이에 조건부인 사전 공격이다(색인 열의 모든 공격에 길이를 추가한 통제 실험은 아님).');
out=out.replace("C-mongo의 같은 anchor ID에서 암호문만 바뀐 경우도 '변경'에 포함했다.","C-mongo의 같은 anchor ID에서 암호문만 바뀐 경우를 집계하는 코드도 준비했으나, 해당 전후 실험은 완료 전에 중단되어 미측정이다.");
out=out.replace('libmongocrypt/blob/master/src/mc-str-encode-string-sets.c','libmongocrypt/blob/3872fc2ad0d1c712d43aaa26eefb49da64e61a62/src/mc-str-encode-string-sets.c');
writeFileSync(`${root}/report-ko.md`,out);console.log('partial report preserved '+(files.length+deltaFiles.length)+'/24');
