import fs from 'node:fs';
const O='bench/results/2026-09-29-task7',read=n=>JSON.parse(fs.readFileSync(`${O}/${n}.json`,'utf8')),r=read('measure'),w=fs.existsSync(O+'/write.json')?read('write'):null,cases=read('cases');
const rows=r.rows.filter(x=>['plain','final','tag'].every(p=>x.summary[p])),f=x=>Number(x).toFixed(3),missing=[];
for(const mode of ['count','list'])for(const c of cases)if(!rows.some(r=>r.name===c.name&&r.mode===mode))missing.push(mode+' '+c.name);
const korean=n=>'all'in n?n.all.some(korean):'any'in n?n.any.some(korean):n.op!=='eq'&&/[\uac00-\ud7af]/u.test(n.value);
const size=t=>Number(r.tables.find(x=>x.table===t).bytes),plain=size('research_u.customers_plain'),body=size('native_verify_main.customers');
let s=`# 과제7 — 개선 B + 회사명 등장별 꼬리표·장부\n\n## 실패·미측정 먼저\n\n- 검색 완료 ${rows.length}/104 조건·작업(52조건×count/목록300). ${missing.length?'아래 미완료 목록은 미측정이며, 일부 반복만 있는 행의 시간을 중앙값으로 보고하지 않는다.':'전 조건 완료.'}\n- 쓰기 ${w?.finished?'완료':'미완료/미측정'}; 완료된 작업만 아래 표에 낸다. ${r.error?'검색 중단: '+r.error.message:''} ${w?.error?'쓰기 오류: '+w.error.message:''}\n- 최신 사용자 지시로 A를 비교에서 제외했다. 평문·최종안·꼬리표안은 모두 예열2+교차7이다. 중단 전 A 측정 원자료는 보존하되 아래 비교에는 넣지 않는다. 첫 실행은 별도1회이며 콜드 캐시라고 부르지 않는다.\n- ${(r.segments?.length??1)>1?'중단 재개로 측정 세션이 나뉘었다. 각 조건 안의3경로는 동일 연결이지만52조건 전체가 하나의 물리 세션이라는 요구는 미충족이다.':'검색은 단일 물리 세션에서 경로를 교차했다.'} 쓰기는 검색과 별도 단일 세션이며 쓰기3경로를 그 세션 안에서 교차한다.\n- 공격 실험은 이번에 하지 않았다. MongoDB식 연구 꼬리표 규칙을 재사용한 것이며 MongoDB 제품 전체의 안전성·성능·사용성을 재현했다고 주장하지 않는다.\n- 회사명 부분검색 토큰·길이·위치는 계속 저장된다. 다른 누출과 결합한 전체 복원 저항은 미검증이다.\n\n## 실제 구현\n\n새 research_u.pb_7_base는 pb_4_improved에서 회사명 정확 후보 ce_company와 정확 판정 salt_company/jx_company를 **제외**해 파생했다. 나머지5칸 정확 검색과6칸 부분 검색은 그대로다. 회사명 꼬리표는 새 pb_7_ctag(tag8,id), 장부는 pb_7_esc(tok,n)이다. 본문은 기존 native_verify_main.customers의 행·필드·scope 결속 인증 암호문을 공유한다.\n\n공유 계약 §4–5와 같은 규칙: t=SHA256(연구키 || customers\\0company\\0e\\0정규화값), 등장i의 tag8=SHA256(t||uint32BE(i))[:8], 장부 키=SHA256(t||esc). DB가 장부에서n을 읽고 generate_series(1,n)으로 꼬리표n개를 만들고 (tag8,id) 색인에서 찾는다. 앱에서 등장 수나 결과ID를 캐시하지 않는다. 기존 C의 대규모 모든필드 표를 사용하지 않고 회사명 정확용10만 꼬리표만 따로 만들었다. 64비트 꼬리표 충돌이 전혀 없다는 암호학적 보장은 아니며 실측 평문 대조를 통과한 범위를 보고한다.\n\n입력은 같은100,000고객·1 scope이고 52조건 전문은 task4 cases.json 그대로다. 반환은 UUID 정렬 LIMIT300 및6칸 정규화값이다. 단어 경계/공백 이름의 조건도 기존 계약상 정규화 부분 문자열 의미다. 기존 표 수정·커밋 없음, 새 표·함수 보존.\n\n## 용량(표·색인·TOAST 포함)\n\n|구성|행 수|바이트|행당 바이트|평문 대비|\n|---|---:|---:|---:|---:|\n`;
for(const [label,n,b]of [['평문',100000,plain],['최종안 본문+검색표',100000,body+size('research_u.pb_4_final')],['꼬리표안 본문+base+꼬리표+장부',100000,body+size('research_u.pb_7_base')+size('research_u.pb_7_ctag')+size('research_u.pb_7_esc')],['꼬리표 표만',100000,size('research_u.pb_7_ctag')],['장부만',16,size('research_u.pb_7_esc')]])s+=`|${label}|${n}|${b}|${f(b/n)}|${f(b/plain)}|\n`;
s+='\n전체 경로의 행당 용량 분모는 고객100,000행이다. 장부만의 행당 값은16개 장부 키 기준이다. 공유 본문은 경로마다 한 번만 더했다.\n\n## 검색 시간\n\nSQL은 클라이언트 요청~응답 왕복 합계, 전체는 토큰 준비·SQL·반환6칸 인증 복호화까지다. 지표별 중앙값이므로 구간을 더한 값과 전체 중앙값은 다를 수 있다. †는 C 로캘 한글 LIKE가 포함되어 평문 대비 성능 주장에서 제외하는 참고치다. 모든 완료 실행에서 count 또는 정렬ID·6칸값을 평문과 단언했다.\n\n|조건·작업|일치/반환|평문 SQL/전체 (=1배)|최종안 SQL/전체|꼬리표 SQL/전체|꼬리표 SQL배율/전체배율|\n|---|---:|---:|---:|---:|---:|\n';
for(const x of rows){s+=`|${x.name}${korean(x.node)?'†':''} ${x.mode}|${x.matches}/${x.returned}|${['plain','final','tag'].map(p=>f(x.summary[p].db)+' / '+f(x.summary[p].total)).join('|')}|${f(x.summary.tag.sqlRatio)} / ${f(x.summary.tag.ratio)}|\n`;}
s+='\n### 조건 전문과 후보\n\n후보는 전체 토큰 조건의 통과 수이며 목록 LIMIT까지 실제 방문한 수와 구분한다. 꼬리표의 회사명 정확 조건은 꼬리표 자체가 최종판정이다.\n\n|조건|전문|최종안 / 꼬리표 후보|\n|---|---|---|\n';
for(const c of cases){const x=rows.find(x=>x.name===c.name);s+=`|${c.name}|${(x?.condition??JSON.stringify(c.node)).replaceAll('|','\\|')}|${x?[x.candidates.final,x.candidates.tag].join(' / '):'미측정'}|\n`;}
s+='\n### 구간·수신·인증 및 첫 실행\n\n|조건·작업|경로|준비 / SQL / 중간 / 후처리 / 전체(ms)|SQL횟수 / 수신행 / 인증칸|첫 SQL / 전체(ms)|\n|---|---|---|---|---|\n';
for(const x of rows)for(const p of ['plain','final','tag']){const z=x.summary[p],a=x.first[p];s+=`|${x.name} ${x.mode}|${p}|${[z.pre,z.db,z.between,z.post,z.total].map(f).join(' / ')}|${z.sql} / ${z.appRows} / ${z.decrypts}|${f(a.db)} / ${f(a.total)}|\n`;}
s+='\n## 쓰기 비교\n\n새 쓰기 전용 pb_7_w_* 표만 사용한다. 삽입300행, 회사명 수정100행(각 행과 다른 기존 fixture 회사값), 삭제100행을 행마다 트랜잭션으로 커밋한다. 꼬리표안은 본문+검색표+장부 upsert/증가+꼬리표 삽입을 원자적으로 처리한다. 수정은 옛 꼬리표를 지우고 새 등장 순번을 발급하며 옛 장부 수는 감소시키지 않는다. 삭제는 본문 FK cascade로 검색표·꼬리표를 지우고 장부는 유지한다.\n\n수정·삭제 라운드의 초기상태는 기존10만행의 장부와 그중300개 실제 행·꼬리표다. 과거에 사라진 등장 순번이 많이 남은 장부 상태를 포함하므로 장부가 실제300행으로 압축된 신규 DB 쓰기로 해석하지 않는다. 삽입 라운드는 빈 표·빈 장부에서 시작한다. 리셋·검증은 시간 밖이다.\n\n|작업|행 수|평문 전체 / 행당(ms)|최종안 전체 / 행당(ms)|꼬리표 전체 / 행당(ms)|꼬리표 평문배율|\n|---|---:|---:|---:|---:|---:|\n';
for(const x of w?.cases??[])if(['plain','final','tag'].every(p=>x.summary[p]))s+=`|${x.op}|${x.rows}|${['plain','final','tag'].map(p=>f(x.summary[p].totalMs)+' / '+f(x.summary[p].perRowMs)).join('|')}|${f(x.summary.tag.ratio)}|\n`;
s+='\n평문 삽입은 원본 fixture의 동일 ID를 INSERT SELECT로 복사하며, 암호 경로는 미리 읽은 같은 값을 인코딩해 VALUES로 삽입한다. SQL 형태 차이를 포함한 이 실험 구현의 시간이다. 꼬리표안의 동시 쓰기·같은 행 경합·중간 실패 롤백은 이번 과제에서 측정 안 함.\n\n|쓰기·경로|준비 / SQL / 중간 / 후처리 / 전체(ms)|SQL회 / 수신행|첫 전체(ms)|\n|---|---|---|---:|\n';
for(const x of w?.cases??[])if(['plain','final','tag'].every(p=>x.summary[p]))for(const p of ['plain','final','tag']){const z=x.summary[p];s+=`|${x.op} ${p}|${[z.preMs,z.dbMs,z.betweenMs,z.postMs,z.totalMs].map(f).join(' / ')}|${z.sqlCalls} / ${z.receivedRows}|${f(x.first[p].totalMs)}|\n`;}
s+=`\n완료된 쓰기 사후 대조 ${w?.checks?.length??0}회. 매번 전체6칸 값을 평문 fixture와 비교하고 회사값별 실제 count를 검증한다. 삭제 장부 불변은 삭제 라운드마다 키·n 전체를 deepEqual한다. ${w?.finished?'삽입·수정·삭제와 장부 불변 검사 완료.':'쓰기 전체 완료 여부는 미검증.'}\n\n## 미완료 목록\n\n${missing.length?missing.join(', '):'검색 없음.'}\n${w?.finished?'쓰기 없음.':'쓰기 미완료/미측정; 부분 원자료는 최종 중앙값과 구분.'}\n\n## 근거·재현\n\n- bench/research-task7/run.ts load: 최초 적재 전용(표가 있으면 중단); measure: 저장된 완료 조건을 건너뛰며 재개.\n- bench/research-task7/write.ts: 최초 쓰기 표 생성·측정, 재실행 시 기존 표 때문에 중단.\n- rtk proxy node bench/research-task7/report.mjs: 보고 재생성. 원자료 ${O}/load.json, measure.json, cases.json, write.json.\n- 보고 생성 ${new Date().toISOString()}; 검색 시작 ${r.started}, 종료 ${r.finished??'진행/중단'}, 세션 ${JSON.stringify(r.segments??[{pid:r.pid}])}.\n\n## 결론 3줄\n\n1. 회사명 등장별 꼬리표·장부 경로를 실제로 적재했고, 완료된 검색은 평문과 일치했다.\n2. 없는 회사와 일부 드문 회사에는 이점이 있지만 흔한 회사·혼합조건에서는 등장 수만큼 꼬리표를 생성·찾는 비용이 커, 모든 조건의 개선안이라고 결론 내릴 수 없다.\n3. 완료 범위·미측정은 위에 구분했으며, 로컬 합성 fixture 결과로서 운영 보장·보안 인증이 아니다.\n`;
if(fs.existsSync(O+'/plans.json')){
 const ps=read('plans');let note='## 추가 계획 확인 — 느림을 전부 해시 비용으로 해석하지 않는다\n\n검색 반복 이후 EXPLAIN (ANALYZE, BUFFERS)를 별도로1회씩 실행했다. 아래 서버 실행 시간은 앞의 SQL 왕복 중앙값과 다른 지표다. 원자료 plans.json.\n\n|조건|최종안 서버 실행(ms)|꼬리표안 서버 실행(ms)|\n|---|---:|---:|\n';
 for(const name of ['exact_common','and4'])note+=`|${name}|${f(ps.find(p=>p.name===name&&p.path==='final').plan[0]['Execution Time'])}|${f(ps.find(p=>p.name===name&&p.path==='tag').plan[0]['Execution Time'])}|\n`;
 note+='\nAND4 최종안은 GIN에서554후보를 읽어62행을 반환했다. 꼬리표안은 꼬리표 색인 결과를10행으로 추정했지만 실제28,331행이었고, 그 ID마다 base 색인을28,331번 조회한 뒤62행을 남겼다. 꼬리표 생성 Function Scan은1회28,331개·46.025ms, 전체 서버 실행은770.563ms여서 **전체 퇴행을 해시 생성 자체만의 비용이라고 볼 수 없다**. 현재 SQL에서의 후보 우선순위·조인 계획과 base 반복 조회가 함께 작용했다. 계획 개선안의 재측정은 이번 범위에 포함하지 않았다.\n\n## 가설 검증\n\n|가설|판정|근거|\n|---|---|---|\n|회사명 꼬리표안의 검색이 평문과 같다|통과(실측 범위)|104조건·작업,3경로×교차7, count·정렬ID·6칸값 대조|\n|회사명 꼬리표로 전체 질의가 빨라진다|기각|없는 회사는 이득, 흔한 회사·AND4·여러 OR에서 퇴행|\n|삭제할 때 장부를 줄이지 않아도 count가 맞는다|통과(실측 범위)|10개 삭제 라운드 장부 전체 불변+회사값별 count 대조|\n|안전성과 동시 쓰기까지 입증했다|미검증|이번 꼬리표안 공격·동시성·실패 주입 실험 없음|\n\n';
 s=s.replace('## 미완료 목록',note+'## 미완료 목록');
 s=s.replace('흔한 회사·혼합조건에서는 등장 수만큼 꼬리표를 생성·찾는 비용이 커','흔한 회사·혼합조건에서는 현재 SQL의 꼬리표 생성·후보 과소추정·base 반복 조회 비용이 커');
}
fs.writeFileSync('.local/research/task7-m1-astra.md',s);console.log(JSON.stringify({complete:rows.length,missing:missing.length,writeDone:!!w?.finished,bytes:Buffer.byteLength(s)}));
